apiVersion: v2
appVersion: 0.1.0
description: Elma365 emlabot proxy
home: https://git.elewise.com/elma365/elmabot-proxy
name: elmabot-proxy
sources:
- dreg.elewise.com:5005/elma365/elmabot-proxy
type: application
version: 0.1.0
