global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-3f872099
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpTimeout: 1m
  identityServerUrl: https://elmaassistanttest.vps.elewise.com:8443
  apiUrl: http://elmaassistanttest.vps.elewise.com:8070
  grantType: elma.assistant.auth.grants.impersonation.elma365
  scope: elma.assistant.scopes.api.gateways.elma365 elma.assistant.scopes.auth.impersonation
  oidcUri:
autoscaling: {}
nameOverride: elmabot-proxy
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "44d1b234"
  ci.elma365.com/checksum: "3f872099"
  ci.elma365.com/job_id: "3511741"
  ci.elma365.com/timestamp: "2025-08-04T11:16:46+04:00"
  ci.elma365.com/pipeline_id: "612150"
