{
 "title": "Elma365 cloud",
 "tags": [ "Elma365" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(up, region)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(http_server_requests_total{region=~\"$cluster\"},namespace)"
   },
   {
    "name": "app",
    "query": "label_values(http_server_requests_total,job)"
   },
   {
    "name": "code",
    "query": "label_values(http_server_requests_total,code)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP request duration - 95e | $cluster",
   "type": "graph",
   "description": "95 процентиль продолжительности HTTP запросов (main)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{namespace=\"staging\",region=~\"$cluster\",job=\"main\"}[5m])) by (le,namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{namespace=\"production\",region=~\"$cluster\",job=\"main\"}[5m])) by (le,namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{namespace=\"elma365-production\",region=~\"$cluster\",job=\"main\"}[5m])) by (le,namespace))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{namespace=\"elma365-staging\",region=~\"$cluster\",job=\"main\"}[5m])) by (le,namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Helm Releases ($namespace)  | $cluster",
   "type": "table-old",
   "description": "Helm релизы",
   "gridPos": { "h": 21, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min(helm_chart_info{exported_namespace=\"$namespace\",region=~\"$cluster\"}) by (chart, release, version) != 2"
    }
   ]
  },
  {
   "title": "Status of containers in $namespace  | $cluster",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(max_over_time(kube_pod_status_phase{phase=\"Succeeded\",exported_namespace=\"$namespace\",region=~\"$cluster\"}[1m]) == 1) * 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(max_over_time(kube_pod_status_phase{phase=\"Running\",exported_namespace=\"$namespace\",region=~\"$cluster\"}[1m]) == 1) * 1",
     "legendFormat": "{{exported_pod}}"
    },
    {
     "expr": "(max_over_time(kube_pod_status_phase{phase=\"Pending\",exported_namespace=\"$namespace\",region=~\"$cluster\"}[1m]) == 1) * 2",
     "legendFormat": "{{exported_pod}}"
    },
    {
     "expr": "(max_over_time(kube_pod_status_phase{phase=\"Failed\",exported_namespace=\"$namespace\",region=\"$cluster\"}[1m]) == 1) * 3",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(max_over_time(kube_pod_status_phase{phase=\"Unknown\",exported_namespace=\"$namespace\",region=~\"$cluster\"}[1m]) == 1) * 4",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connectivity over HTTPS  | $cluster",
   "type": "graph",
   "description": "Сетевые задержки до ряда внешних ресурсов",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (probe_http_duration_seconds{region=~\"$cluster\"}) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean packet loss | $cluster",
   "type": "graph",
   "description": "Сетевые потери между нодами кластера и до ряда внешних ресурсов.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( \n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{region=~\"$cluster\"}[45s]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{region=~\"$cluster\"}[45s]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{region=~\"$cluster\"}[45s]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mail generate body duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(quickbpm_generate_body_duration_seconds_bucket{namespace=\"elma365-staging\",region=~\"$cluster\",job=\"mailer\"}[5m])) by (le,namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(quickbpm_generate_body_duration_seconds_bucket{namespace=\"staging\",region=~\"$cluster\",job=\"mailer\"}[5m])) by (le,namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(quickbpm_generate_body_duration_seconds_bucket{namespace=\"elma365-production\",region=~\"$cluster\",job=\"mailer\"}[5m])) by (le,namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(quickbpm_generate_body_duration_seconds_bucket{namespace=\"production\",region=~\"$cluster\",job=\"mailer\"}[5m])) by (le,namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Emails Sent ($namespace) | $cluster",
   "type": "gauge",
   "description": "Счетчик отправленных писем за посление 24 часа",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (delta(quickbpm_mailer_success_emails_total{region=~\"$cluster\",namespace=\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Mailer Stats | $cluster",
   "type": "graph",
   "description": "График проблем с отправкой писем",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0 - round(sum by (region,namespace) (increase(quickbpm_mailer_mailbox_disabled_total{region=~\"$cluster\"}[5m]) >= 0))",
     "legendFormat": "Mail Sending error {{region}}/{{namespace}}"
    },
    {
     "expr": "0 - round(sum by (region,namespace) (increase(quickbpm_mailer_error_emails_total{region=~\"$cluster\",important=\"true\"}[5m]) >= 0))",
     "legendFormat": "Mail Delivery unknown error {{region}}/{{namespace}}"
    },
    {
     "expr": "round(sum by (region,namespace) (increase(quickbpm_mailer_error_emails_total{region=~\"$cluster\",important=\"false\"}[5m]) >= 0))",
     "legendFormat": "Mail Delivery user error {{region}}/{{namespace}}"
    }
   ]
  },
  { "title": "Support Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Support messages | $cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0 - round(sum by (namespace) (increase(quickbpm_main_error_support_messages_total{region=~\"$cluster\",namespace=\"$namespace\"}[5m])) >= 0 )",
     "legendFormat": "failed messages to operators {{$cluster}}"
    },
    {
     "expr": "round(sum by (namespace) (increase(quickbpm_main_success_support_messages_total{region=~\"$cluster\",namespace=\"$namespace\"}[5m])) >=0 )",
     "legendFormat": "successful messages to operators {{$cluster}}"
    },
    {
     "expr": "0 - round(sum by (namespace) (increase(quickbpm_support_error_clients_messages_total{region=~\"$cluster\",namespace=\"$namespace\"}[5m])) >= 0 )",
     "legendFormat": "failed messages to clients {{$cluster}}"
    },
    {
     "expr": "round(sum by (namespace) (increase(quickbpm_support_success_clients_messages_total{region=~\"$cluster\",namespace=\"$namespace\"}[5m])) >=0 )",
     "legendFormat": "successful messages to clients {{$cluster}}"
    }
   ]
  },
  {
   "title": "Company Deployments | $cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "0 - round(sum by (namespace) (increase(elma365_deploy_create_company_total{code!=\"201\",region=~\"$cluster\"}[5m])))",
     "legendFormat": "fail {{namespace}}"
    },
    {
     "expr": "round(sum by (namespace) (increase(elma365_deploy_create_company_total{code=\"201\",region=~\"$cluster\"}[5m])))",
     "legendFormat": "success {{namespace}}"
    }
   ]
  },
  {
   "title": "Activation not from blanc | $cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (namespace) (increase(elma365_vahter_trial_activations_not_from_blank_count_by_params{region=~\"$cluster\"}[3m])))"
    }
   ]
  },
  {
   "title": "Trial activation | $cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0 - round(sum by (namespace) (increase(elma365_vahter_trial_activations_count_by_code{code!=\"201\",region=~\"$cluster\"}[3m])))",
     "legendFormat": "fail {{namespace}}"
    },
    {
     "expr": "round(sum by (namespace) (increase(elma365_vahter_trial_activations_count_by_code{code=\"201\",region=~\"$cluster\"}[3m])))",
     "legendFormat": "success {{namespace}}"
    }
   ]
  },
  {
   "title": "Activation duration | $cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(elma365_vahter_trial_activation_from_blank_duration_seconds_bucket{region=~\"$cluster\"}[3m])) by (le,namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Requests per second per ingress controller | $cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total{region=\"$cluster\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Requests per second per service | $cluster | $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(http_server_requests_total{region=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  { "title": "Panics | $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Staging: Panic | $cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (quickbpm_panic_counter{region=\"$cluster\",exported_namespace=~\"(staging|elma365-staging)\"})",
     "legendFormat": "{{ exported_instance }} | {{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Production: Panic | $cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(exported_instance) (quickbpm_panic_counter{region=\"$cluster\",exported_namespace=~\"(production|elma365-production)\"})",
     "legendFormat": "{{ exported_instance }} | {{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "HTTP status codes for $app  (per minute) | $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "repeat": "app"
  },
  {
   "title": "Staging: $app | $cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"staging\", region=~\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "quickbpm|code:{{gcode}}xx"
    },
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"elma365-staging\", region=~\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "elma365|code:{{gcode}}xx"
    }
   ]
  },
  {
   "title": "Production: $app | $cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"production\", region=\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "quickbpm|code:{{gcode}}xx"
    },
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"elma365-production\", region=\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "elma365|code:{{gcode}}xx"
    }
   ]
  },
  {
   "title": "HTTP status codes for $app  (per minute) | $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 }
  },
  {
   "title": "Staging: $app | $cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"staging\", region=~\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "quickbpm|code:{{gcode}}xx"
    },
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"elma365-staging\", region=~\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "elma365|code:{{gcode}}xx"
    }
   ]
  },
  {
   "title": "Production: $app | $cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"production\", region=\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "quickbpm|code:{{gcode}}xx"
    },
    {
     "expr": "sum(label_replace(round(delta(http_server_requests_total{job=\"$app\",namespace=\"elma365-production\", region=\"$cluster\", code=~\"[2|3|4|5].*\"}[1m])),\"gcode\",\"$1\",\"code\",\"(^.)[0-9]{2}\")) by (namespace,gcode)",
     "legendFormat": "elma365|code:{{gcode}}xx"
    }
   ]
  }
 ]
}