global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    rabbitmqQueueLength: 500
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
    lowcode:
      internalOtlpHttpPort: 3001
  openshift: false
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  gatewayresources: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  runtimeSchemaCacheMemoryLimit: 0
  setupJobTtlSecondsAfterFinished:
  maxScriptTimeoutSeconds: 600
  defaultScriptTimeoutSeconds: 60
images:
  worker: ci-9f56f39b
  gateway: ci-a5760cf0
  setup: ci-62970d76
image:
  repository: {}
  pullSecret: {}
gateway:
  podAnnotations: {}
lifecycle:
  preStop:
    httpGet:
      path: prestop
      port: 3000
      scheme: HTTP
appconfig:
  httpProxyAddr: ''
  concurrency: 4
  forkAvailableMemorySize: 0
  skipCompilationLimits: "false"
  multipartUploadChunkSize: 32
  pingTimeoutMs: 300
  pingIntervalMs: 400
  scriptExchange: "script"
  scriptAlternateExchange: "script-default"
  defaultScriptQueue: "script.default"
fetch:
  retry:
    strategy: "linear"
    maxCount: "3"
    delay: "1000"
    exponentialCoefficient: "2"
fullnameOverride: worker
nameOverride: worker
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
gatewayresources:
  requests:
    memory: "850Mi"
    cpu: "200m"
  limits:
    memory: "1024Mi"
    cpu: "500m"
gatewayautoscaling: {}
autoscaling: {}
service:
  http_port_wrk: 3000
networkPolicy:
  allowIPLocalDns:
    - 169.254.25.10/32
    - 169.254.20.10/32
    - 10.96.128.2/32
  allowPortLocalDns:
    - 53
  allowAllIPexcept:
    - 10.96.0.0/16
    - 10.100.0.0/16
    - 10.111.0.0/16
    - 10.222.0.0/16
  allowNamespaceName:
    - elma365-adds
    - elma365-applets
    - linkerd
  allowDnsLabel:
    - key: k8s-app
      value: kube-dns
    - key: k8s-app
      value: node-local-dns
  allowIngressLabel:
    - key: app.kubernetes.io/name
      value: ingress-nginx
  rabbitMQSelectors:
    - key: app
      operator: In
      values:
        - rabbitmq
        - rabbitmq-ha
annotations:
  ci.elma365.com/commit: "6bc41681"
  ci.elma365.com/checksum: "9f56f39b"
  ci.elma365.com/job_id: "3708989"
  ci.elma365.com/timestamp: "2025-09-30T11:07:13+04:00"
  ci.elma365.com/pipeline_id: "629087"
