global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  companies:
  openshift: false
  autoGenerationJwtDisabled: false
  cronStartingDeadlineSeconds: ""
  cronTtlSecondsAfterFinished: ""
  cronActiveDeadlineSeconds: ""
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  multi: false
images:
  vahter: ci-3005841a
image:
  repository: {}
  pullSecret: {}
nameOverride: vahter
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "128Mi"
    cpu: "150m"
  limits:
    memory: "256Mi"
    cpu: "1000m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
insertDefaults: false
appconfig:
  activateTimeout: 5m
  allowInsecureCookie: false
  easyAuthTokenTTL: 5m
  corsHosts:
    production:
      - elma365.ru
      - elma365.net
      - elma365.eu
      - elma365.com
    staging:
      - s-elma365.ru
      - s-elma365.net
      - s-elma365.eu
      - s-elma365.com
    _default:
      - '*'
  secondFactor:
    limitAttempts: 3
    codeLength: 4
    codeLifetime: 2m
    excludedIPNets: ''
  planChangePassword:
    schedule: "0 16 19 5 *"
  verificationProvider:
    testCode: ''
  extendedAuth:
    codeTTL: 2m
    maxFailsCount: 3
mongodb:
  dbName: "elma365"
  migrationCollectionPrefix: "vahter"
  collectionNamePrefix: ""
  appendServiceNameToPrefix: false
ingress:
  paths:
    - /guard
  annotations: {}
secrets:
  renewToken:
    enabled: false
    schedule: "0 * * * *"
    oldTokenExpiry: "2025-02-19"
    certNew: ""
    keyNew: ""
  tls:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIC4DCCAkmgAwIBAgIJAI5CeUT3SGdCMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYD
      VQQGEwJSVTEQMA4GA1UECAwHSXpoZXZzazEQMA4GA1UEBwwHSXpoZXZzazENMAsG
      A1UECgwERWxtYTEQMA4GA1UECwwHZWxtYTM2NTEUMBIGA1UEAwwLZWxtYTM2NS5j
      b20xHjAcBgkqhkiG9w0BCQEWD2VsbWEzNjVAbWFpbC5ydTAeFw0xNzExMjgwOTA5
      MjhaFw0xNzEyMjgwOTA5MjhaMIGIMQswCQYDVQQGEwJSVTEQMA4GA1UECAwHSXpo
      ZXZzazEQMA4GA1UEBwwHSXpoZXZzazENMAsGA1UECgwERWxtYTEQMA4GA1UECwwH
      ZWxtYTM2NTEUMBIGA1UEAwwLZWxtYTM2NS5jb20xHjAcBgkqhkiG9w0BCQEWD2Vs
      bWEzNjVAbWFpbC5ydTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA4jc+MhV2
      NXC9tfN9+TguqbSlVE6H0u9kg7voy8ZdW0ZhJumL1Wc/BiBop8FzUu9xWZNZLl1w
      vIPH4jQ/AumeLAlGuERKWlwwUo8hk4nSmXX+TUFyJhcVP6ykU0xC6eziKTikjiMe
      LRWN4NV/AXXsBsnMrqPCN14q46qzgDkaMekCAwEAAaNQME4wHQYDVR0OBBYEFB+I
      gCz+TtJZZZiQ8lp+GSVZgpSQMB8GA1UdIwQYMBaAFB+IgCz+TtJZZZiQ8lp+GSVZ
      gpSQMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADgYEAvB6j7uoTqzC3Q26U
      dif5/sLjomRlHxnH4wQTQOnH2l61T8bUiC0JYi+99SjP2U4G23B+SEeKCXA/Srpj
      08L1JYXKYFX7kAAULraLStAbgDt5T+rGNuCdiB8CmCI/NoIBaByIREKzbWU5A9HA
      o18prQZkJAzQRFcp/Up/ATL+f30=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXAIBAAKBgQDiNz4yFXY1cL218335OC6ptKVUTofS72SDu+jLxl1bRmEm6YvV
      Zz8GIGinwXNS73FZk1kuXXC8g8fiND8C6Z4sCUa4REpaXDBSjyGTidKZdf5NQXIm
      FxU/rKRTTELp7OIpOKSOIx4tFY3g1X8BdewGycyuo8I3XirjqrOAORox6QIDAQAB
      AoGAIYiU5LG/wy5CQR2mN/J3IFsSAwxdIAyytsB9Qu/V2Pj23+DRBMJ4Wj0lpnCL
      2uh5whCQsMnTM27Ji6O5D4J4GsGYNvU0hPhoITcuj88T3xCZZ3Zsb/42Rphp/IVm
      7+ssg7WNhDo3KwixS/pSr2zMmh9oNWOOfHviyFrviQ9xBbECQQD9YW525GcliQH1
      JR6pB+4C+Y72qQ5E2Nq43SlF75nUm4LnnFypo6PGuvWaAXs0z9R2MWcCu7ub+GIC
      m38FQhGtAkEA5I3rj2G6sUnbmEd6ZRvGPGFrDckbwbusvZXB+w+9jdD+2qhICb1v
      WxhBzjH7lSSNSj5EIWkj+TzNqQuX7k1ArQJAGRSG0Z/kEdQQ7IoDEeomBgdbvlCX
      h/sLE1dY2YJQ8Ll/6JsSlPwMnwQsgVT6NA0KU7SqJJwegt7AHM/1b7jNdQJAY+Eh
      cCdlTtTYAlQ6SLU6jGiGQCAC4UcC1lb7zpuyWqdauHOSB6+hWk3fdByjtSmkFS3g
      2Dj6X5ESzy0h2CIqgQJBANtYPfvXn4TDx3nPoDCeriUE/vzxaRmigFqz5nIyJ6I5
      CbQI9DQ6mLFx6i0J5h/753UONHu8c6N05A0ARH5S4Us=
      -----END RSA PRIVATE KEY-----
annotations:
  ci.elma365.com/commit: "e791c6dd"
  ci.elma365.com/checksum: "3005841a"
  ci.elma365.com/job_id: "3510729"
  ci.elma365.com/timestamp: "2025-08-04T11:12:35+04:00"
  ci.elma365.com/pipeline_id: "612112"
