{{- if or .Values.appconfig.allowExport .Values.appconfig.allowImport }}
apiVersion: v1
kind: Secret
metadata:
  name: intercluster
  labels:
    {{- include "intercluster.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  key: {{ print "value" | b64enc | quote }}

{{- if eq (toString .Values.ingress.enabled) "true" }}
{{- if .Values.ingress.password }}
  # пароль для ingress
  auth: {{ default "wrongvalue" (print "apiuser:{PLAIN}" (index .Values.ingress.password)) | b64enc | quote }}
{{- end }}
{{- end }}

{{- end }}
