{{- define "helm-library.hpa" }}
{{- $name := include "helm-library.name" . }}
{{- if or ( eq .Values.global.edition "enterprise" ) ( not ( eq .Values.global.solution "onPremise" ) ) }}
{{- if or .Values.global.autoscaling.enabled .Values.autoscaling.enabled }}
{{- if eq .Values.global.autoscaling.type "hpa" }}
{{- $dbsExporterService := .Values.global.monitoring.rmqExporterName | default "dbsexporter-rabbitmq" -}}
{{- if semverCompare "<1.23-0" (include "kubeVersion" .) }}
apiVersion: autoscaling/v2beta1
{{- else -}}
apiVersion: autoscaling/v2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  labels:
  {{- include "helm-library.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ .Values.autoscaling.minReplicas | default .Values.global.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default .Values.global.autoscaling.maxReplicas }}
  metrics:
    {{- if or .Values.global.autoscaling.targetMemoryUtilizationPercentage .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "kubeVersion" $) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | default .Values.global.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | default .Values.global.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if or .Values.global.autoscaling.targetCPUUtilizationPercentage .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "kubeVersion" $) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default .Values.global.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default .Values.global.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if eq (toString .Values.global.monitoring.provisioner) "deckhouse" }}
    {{- if eq $name "worker-gateway" }}
    - type: External
      external:
        metric:
          name: elma365_worker_gateway
          selector:
            matchLabels:
              namespace: {{ .Release.Name }}
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ .Values.autoscaling.rabbitmqQueueLength | default .Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- if eq $name "contractor" }}
    - type: External
      external:
        metric:
          name: elma365_contractor
          selector:
            matchLabels:
              namespace: {{ .Release.Name }}
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ .Values.autoscaling.rabbitmqQueueLength | default .Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- if eq $name "diskjockey" }}
    - type: External
      external:
        metric:
          name: elma365_diskjockey
          selector:
            matchLabels:
              namespace: {{ .Release.Name }}
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ .Values.autoscaling.rabbitmqQueueLength | default .Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- if eq $name "dup-detector" }}
    - type: External
      external:
        metric:
          name: elma365_dup_detector
          selector:
            matchLabels:
              namespace: {{ .Release.Name }}
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ .Values.autoscaling.rabbitmqQueueLength | default .Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- if eq $name "postman" }}
    - type: External
      external:
        metric:
          name: elma365_postman
          selector:
            matchLabels:
              namespace: {{ .Release.Name }}
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ .Values.autoscaling.rabbitmqQueueLength | default .Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- if eq $name "processor" }}
    - type: External
      external:
        metric:
          name: elma365_processor
          selector:
            matchLabels:
              namespace: {{ .Release.Name }}
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ .Values.autoscaling.rabbitmqQueueLength | default .Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
