{{- define "helm-library.servicemonitor-worker" }}
{{- $dot := required "GlobalContext should be passed" .GlobalContext }}
{{- $localContext := required "LocalContext should be passed" .LocalContext }}
{{- $name := required "Name should be passed" $localContext.name }}
{{- $inputParams := .}}

{{- if or (eq $dot.Values.global.edition "enterprise") (not (eq $dot.Values.global.solution "onPremise")) }}
{{- if eq (toString $dot.Values.global.monitoring.enabled) "true" }}
{{- if ($dot.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: {{ $name }}
    {{- if eq (toString $dot.Values.global.monitoring.provisioner) "deckhouse" }}
    prometheus: main
    {{- end }}
    {{- if $dot.Values.global.monitoring.serviceMonitor }}
    {{- if $dot.Values.global.monitoring.serviceMonitor.labels }}
    {{- with $dot.Values.global.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- end }}
  name: {{ $name }}-servicemonitor
spec:
  endpoints:
  - port: http-metrics
    {{- if ne (toString $dot.Values.global.monitoring.provisioner) "deckhouse" }}
    path: /metrics
    interval: {{ default "30s" $dot.Values.global.monitoring.metrics.interval }}
    honorLabels: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- end }}
    {{- if $dot.Values.global.monitoring }}
    {{- if $dot.Values.global.monitoring.metrics }}
    metricRelabelings:
      {{- if $dot.Values.global.monitoring.serviceMonitor }}
      {{- if $dot.Values.global.monitoring.serviceMonitor.metricRelabelings }}
      {{- with $dot.Values.global.monitoring.serviceMonitor.metricRelabelings }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- else }}
      {{- if ne (toString $dot.Values.global.monitoring.metrics.all) "true" }}
      - sourceLabels: [ __name__ ]
        regex: (elma365_common_cache_.+|elma365_common_redis_.+|elma365_common_postgresql_.+|rabbitmq_.+|.*_histogram_.*|.*_bucket)
        # regex: (elma365_common_cache_.+|elma365_common_redis_.+|elma365_common_postgresql_.+|rabbitmq_.+|eventbus_.+|.*_histogram_.*|.*_bucket)
        # regex: (elma365_common_redis_.+|elma365_common_postgresql_query_execution_time_histogram_.*|eventbus_delivery_duration_bucket|rabbitmq_.+) # worker_script_compile_time_histogram_bucket
        action: drop
      {{- end }}
      - targetLabel: region
        replacement: {{ printf "%s-%s-%s" $dot.Release.Namespace $dot.Values.global.solution $dot.Values.global.edition }}
        action: replace
      - targetLabel: cluster
        replacement: {{ printf "%s" $dot.Values.global.host | replace "." "-" | quote }}
        action: replace
      {{- end }}
      {{- else }}
      {{- if ne (toString $dot.Values.global.monitoring.metrics.all) "true" }}
      - sourceLabels: [ __name__ ]
        regex: (elma365_common_cache_.+|elma365_common_redis_.+|elma365_common_postgresql_.+|rabbitmq_.+|.*_histogram_.*|.*_bucket)
        # regex: (elma365_common_cache_.+|elma365_common_redis_.+|elma365_common_postgresql_.+|rabbitmq_.+|eventbus_.+|.*_histogram_.*|.*_bucket)
        # regex: (elma365_common_redis_.+|elma365_common_postgresql_query_execution_time_histogram_.*|eventbus_delivery_duration_bucket|rabbitmq_.+) # worker_script_compile_time_histogram_bucket
        action: drop
      {{- end }}
      - targetLabel: region
        replacement: {{ printf "%s-%s-%s" $dot.Release.Namespace $dot.Values.global.solution $dot.Values.global.edition }}
        action: replace
      - targetLabel: cluster
        replacement: {{ printf "%s" $dot.Values.global.host | replace "." "-" | quote }}
        action: replace
      {{- end }}
    relabelings:
      {{- if $dot.Values.global.monitoring.serviceMonitor }}
      {{- if $dot.Values.global.monitoring.serviceMonitor.relabelings }}
      {{- with $dot.Values.global.monitoring.serviceMonitor.relabelings }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- else }}
    - sourceLabels: [__name__]
      targetLabel: region
      replacement: {{ printf "%s" $dot.Values.global.host | replace "." "-" | quote }}
    - sourceLabels: [__name__]
      targetLabel: cluster
      replacement: {{ printf "%s" $dot.Values.global.host | replace "." "-" | quote }}
      {{- end }}
      {{- else }}
    - sourceLabels: [__name__]
      targetLabel: region
      replacement: {{ printf "%s" $dot.Values.global.host | replace "." "-" | quote }}
    - sourceLabels: [__name__]
      targetLabel: cluster
      replacement: {{ printf "%s" $dot.Values.global.host | replace "." "-" | quote }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ $name }}
  namespaceSelector:
    matchNames:
      - {{ $dot.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
