global:
## Настройки provisioner (k8s, deckhouse)
  provisioner: "k8s"
loki:
# -- Режим развертывания позволяет указать способ развертывания Loki.
  deploymentMode: SimpleScalable
# -- Использовать шлюз GEL, если false, будет использоваться шлюз nginx по умолчанию.
  enterprise:
    gelGateway: false
# -- Включение кеширование фрагментов на основе memcached
  chunksCache:
    enabled: false
  loki:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 650m
        memory: 900Mi 
    # -- Включение аутентификации
    auth_enabled: false
    # -- Конфигурация хранилища.
    storage:
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      type: s3
      s3:
        s3: null
        endpoint: master.sale.elewise.com:9000
        region: ru-central-1
        secretAccessKey: SecretPassword
        accessKeyId: elma365user
        signatureVersion: null
        s3ForcePathStyle: true
        insecure: false
        # -- Использовать SSL для подключения к S3
        http_config: {}


    # -- Дополнительная конфигурация уплотнителя
    compactor:
      delete_request_store: s3
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      working_directory: /var/loki/chunks
    # -- Настройка схемы
    schemaConfig:
      configs:
      - from: "2025-08-08"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v13
        store: tsdb
    useTestSchema: false
    # -- Конфигурация лимитов
    limits_config:
      # max_label_name_length: 500
      # max_label_value_length: 800   
      # max_streams_per_user: 20000
      retention_period: 360h #default 744h
      # per_stream_rate_limit: 512M
      # per_stream_rate_limit_burst: 1024M
    commonConfig:
      replication_factor: 1
  # -- Конфигурация модулей записи
  write:
    replicas: 1
  # -- Конфигурация модулей чтения
  read:
    replicas: 1
  # -- Конфигурация модулей бэкенда
  backend:
    replicas: 1
  # -- Конфигурация модулей шлюза
  gateway:
    enabled: true
    replicas: 1
    verboseLogging: true
  # -- Раздел для настройки дополнительного теста Helm
  test:
    enabled: false
  # Канарейка Loki
  lokiCanary:
    enabled: false
  # -- параметры подключения к приватному registry
  sidecar:
    image:
      repository: hub.elma365.tech/docker/addons/kiwigrid/k8s-sidecar
      tag: 1.27.5
  global:
    clusterDomain: "cluster.local"
    image:
      registry: hub.elma365.tech/docker/addons
  # imagePullSecrets: []
  memcached:
      image:
        repository: hub.elma365.tech/docker/addons/memcached
        tag: 1.6.23-alpine
  memcachedExporter:
    image:
      repository: hub.elma365.tech/docker/addons/prom/memcached-exporter
      tag: v0.14.2

# -- Настройка promtail
promtail:
  daemonset:
    # -- Развертывает Promtail как DaemonSet
    enabled: true
    autoscaling:
      enabled: false
  deployment:
    # -- Развертывает Promtail как Deployment
    enabled: false
    replicaCount: 1
  # -- Конфигурация Promtail
  config:
    enabled: true
    serverPort: 3101
    clients:
      - url: http://loki-gateway/loki/api/v1/push
  # -- параметры подключения к приватному registry
  global:
    imageRegistry: "hub.elma365.tech/docker/addons"
    imagePullSecrets: []
