{{- if .Values.serviceAccount.create -}}
{{- $out := . -}}
{{- range $val := .Values.instances }}
{{- with $out -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-mongodb-exporter.serviceAccountName" . }}-{{ $val.name }}
  labels:
    {{- include "prometheus-mongodb-exporter.labels" . | nindent 4 }}
---
{{- end -}}
{{- end }}
{{- end }}