# JWT secret
kind: Secret
apiVersion: v1
type: tls
data:
  tls.key: {{ .Values.secrets.tls.key | b64enc }}
  tls.crt: {{ .Values.secrets.tls.cert | b64enc }}
metadata:
  name: auth-jwt
  labels:
    {{- include "auth.labels" . | nindent 4 }}
---
{{- if (pluck .Values.global.env .Values.secrets.vahter.create | first | default .Values.secrets.vahter.create._default) }}
# Vahter JWT certificate
kind: Secret
apiVersion: v1
type: tls
data:
  tls.crt: {{ .Values.secrets.vahter.cert | b64enc }}
metadata:
  name: vahter-jwt
  labels:
    {{- include "auth.labels" . | nindent 4 }}
{{- end }}