{
 "title": "aspose-actions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, region)" } },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(up{job=~\"main\",cluster=~\"$cluster\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{namespace=~\"^($namespace)$\",container=\"aspose-actions\"})",
     "legendFormat": "aspose-actions"
    }
   ]
  },
  {
   "title": "plain text request in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{namespace=~\"^($namespace)$\", container=\"aspose-actions\", endpoint=\"/asposeactionspb.TemplateProvider/ProcessPlainTextStream\"})",
     "legendFormat": "ProcessPlainTextStream"
    },
    {
     "expr": "sum(http_requests_in_progress{namespace=~\"^($namespace)$\", container=\"aspose-actions\", endpoint=\"/asposeactionspb.TemplateProvider/ProcessPlainText\"})",
     "legendFormat": "ProcessPlainText"
    }
   ]
  },
  {
   "title": "Memory usage in mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "$A / 1000000", "type": "math" },
    { "expression": "$B / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Plain Text Stream avg time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "cpu usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(system_runtime_cpu_usage{namespace=~\"^($namespace)$\",container=\"aspose-actions\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(system_runtime_cpu_usage{namespace=~\"^($namespace)$\",container=\"aspose-actions\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max(system_net_http_http_client_open_connections{namespace=~\"^($namespace)$\",container=\"aspose-actions\"})",
     "legendFormat": "aspose-actions"
    }
   ]
  }
 ]
}