apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "hydra-adaptor.labels" . | nindent 4 }}
  name: "hydra-adaptor"
data: {}
