global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  companies:
    - '*'
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  startupProbe: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
  notifierV2: false
images:
  notifier: ci-d4665d5b
  setup: ci-846aa40a
image:
  repository: {}
  pullSecret: {}
appconfig:
  push:
    fcmKey: ""
    fcmKeyPath: "/etc/notifier/fcm-key.json"
    vapidPublicKey: ""
    vapidPrivateKey: ""
    hmsClientId: ""
    hmsClientSecret: ""
    rustoreProjectId: ""
    rustoreToken: ""
  itemUpdatedConcurrencyCount: 100
  observableCollectionEventsConcurrencyCount: 100
  pushProtocol: elma365
ingress:
  annotations: {}
autoscaling: {}
nameOverride: notifier
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "768Mi"
    cpu: "150m"
  limits:
    memory: "1536Mi"
    cpu: "555m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "e596a375"
  ci.elma365.com/checksum: "846aa40a"
  ci.elma365.com/job_id: "3511215"
  ci.elma365.com/timestamp: "2025-08-04T11:14:52+04:00"
  ci.elma365.com/pipeline_id: "612130"
