apiVersion: v2
appVersion: 0.1.0
description: Elma365 deploy service
home: https://git.elewise.com/elma365/deploy
name: deploy
sources:
- dreg.elewise.com:5005/elma365/deploy
type: application
version: 0.1.0
