{{- if ne (toString .Values.global.solution) "onPremise" }}
{{- if pluck .Values.global.env .Values.jobs.watchDeletedCompanies.enabled | first | default .Values.jobs.watchDeletedCompanies.enabled._default }}
{{- if semverCompare ">=1.21-0" (include "kubeVersion" .) -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: mailer-watch-deleted-companies
  labels:
    {{- include "mailer.labels" . | nindent 4 }}
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  startingDeadlineSeconds: {{ default 300 .Values.global.cronStartingDeadlineSeconds }}
  concurrencyPolicy: Replace
  schedule: '{{ .Values.jobs.watchDeletedCompanies.period }}'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ default 300 .Values.global.cronTtlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ default 120 .Values.global.cronActiveDeadlineSeconds }}
      template:
        metadata:
          labels:
            job: mailer-watch-deleted-companies
            tier: elma365
            sidecar.istio.io/inject: "false"
          annotations:
            linkerd.io/inject: disabled
        spec:
          {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.job.podSecurityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.scheduling" . | indent 10 }}
          {{- end }}
          imagePullSecrets:
          {{- range .Values.global.image.pullSecret }}
            - name: {{ . }}
          {{- end }}
          containers:
            - name: mailer-watch-deleted-companies-curl
              image: "{{ .Values.global.image.repository }}/docker/toolkit/curl:8.2.1"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              args:
                - /bin/sh
                - -ec
                - 'curl --fail -m {{ default 60 .Values.global.cronActiveDeadlineSeconds }} -X POST http://{{ template "mailer.name" . }}:{{ .Values.global.http_port }}/jobs/watchDeletedCompanies'
            {{- if .Values.global.helmLibrary }}
              securityContext:
                {{- include "helm-library.job.securityContext" . | nindent 16 }}
              {{- include "helm-library.cronjobs.resources" . | indent 14 }}
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
{{- end }}
