apiVersion: v1
kind: Secret
metadata:
  name: elma365-secrets
  labels:
    tier: elma365
    configuration: global
  annotations:
    # helm.sh/hook: pre-install
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:

{{- if .Values.global.secretKey }}
  ELMA365_SECRET_KEY:  {{ default "12345678901234567890123456789012" .Values.global.secretKey | b64enc | quote }}
{{- else }}
  ELMA365_SECRET_KEY:  {{ print "12345678901234567890123456789012" | b64enc | quote }}
{{- end }}
