{
 "title": "MinIO Dashboard",
 "tags": [
  "DB",
  "MinIO"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(minio_node_process_starttime_seconds,pod)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job!=\"node-exporter\", job=\"$dbs_pod_name\"},job)"
    }
   },
   {
    "name": "dbs_pod_name",
    "label": "dbs_pod_name",
    "query": {
     "query": "label_values({pod=\"$pod\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "time() - max(minio_node_process_starttime_seconds{pod=\"$pod\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total S3 Traffic Inbound",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_received_bytes{pod=\"$pod\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{pod=\"$pod\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{pod=\"$pod\"}) by (instance))",
       "legendFormat": "Used"
      },
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{pod=\"$pod\"}) by (instance)) ",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Data Usage Growth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "minio_cluster_usage_total_bytes{pod=\"$pod\"}",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Object size distribution",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "minio_cluster_objects_size_distribution{pod=\"$pod\"}",
       "legendFormat": "{{range}}"
      }
     ]
    },
    {
     "title": "Total Open FDs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (minio_node_file_descriptor_open_total{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Total S3 Traffic Outbound",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Total Goroutines",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (server,instance) (minio_node_go_routine_total{pod=\"$pod\"})"
      }
     ]
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"minio-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"^($node)$\"} - node_memory_MemFree_bytes{job=~\"^($node)$\"} - node_memory_Buffers_bytes{job=~\"^($node)$\"} - node_memory_Cached_bytes{job=~\"^($node)$\"} - node_memory_Slab_bytes{job=~\"^($node)$\"} - node_memory_PageTables_bytes{job=~\"^($node)$\"} - node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=~\"^($node)$\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"^($node)$\"} - node_memory_SwapFree_bytes{job=~\"^($node)$\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "container_memory_usage_bytes{container!=\"POD\", pod=~\"minio-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=~\"minio.*\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_receive_bytes_total{pod=~\"minio.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=~\"minio.*\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_transmit_bytes_total{pod=~\"minio.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    },
    {
     "expr": "rate(container_fs_reads_total{container!=\"POD\", pod=~\"minio-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}} {{device}} - Read bytes"
    },
    {
     "expr": "rate(container_fs_writes_total{container!=\"POD\", pod=~\"minio.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}} {{device}} - Writes bytes"
    }
   ]
  },
  {
   "title": "Minio Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Offline Servers",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "minio_cluster_nodes_offline_total{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Total Offline Drives",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "minio_cluster_drive_offline_total{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Number of Objects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_usage_object_total{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "S3 API Data Received Rate ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Data Received [{{server}}]"
      }
     ]
    },
    {
     "title": "S3 API Data Sent Rate ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Data Sent [{{server}}]"
      }
     ]
    },
    {
     "title": "Total Online Servers",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "minio_cluster_nodes_online_total{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Time Since Last Scan Activity",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minio_usage_last_activity_nano_seconds{pod=\"$pod\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Number of Buckets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_bucket_total{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Time Since Last Heal Activity",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minio_heal_time_last_activity_nano_seconds{pod=\"$pod\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Online Drives",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "minio_cluster_drive_online_total{pod=\"$pod\"}",
       "legendFormat": "Total online drives in MinIO Cluster"
      }
     ]
    },
    {
     "title": "S3 API Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_total{pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{server,api}}"
      }
     ]
    },
    {
     "title": "S3 API Request 4xx Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total{pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{server,api}}"
      }
     ]
    },
    {
     "title": "S3 API Request 5xx Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total{pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{server,api}}"
      }
     ]
    },
    {
     "title": "Internode Data Transfer",
     "type": "timeseries",
     "description": "Total number of bytes received and sent among all MinIO server instances",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(minio_inter_node_traffic_sent_bytes{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Internode Bytes Received [{{server}}]"
      },
      {
       "expr": "rate(minio_inter_node_traffic_received_bytes{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Internode Bytes Sent [{{server}}]"
      }
     ]
    },
    {
     "title": "Healing",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_heal_objects_heal_total{pod=\"$pod\"})",
       "legendFormat": "Objects healed in current self heal run"
      },
      {
       "expr": "sum by (instance) (minio_heal_objects_error_total{pod=\"$pod\"})",
       "legendFormat": "Heal errors in current self heal run"
      },
      {
       "expr": "sum by (instance) (minio_heal_objects_total{pod=\"$pod\"}) ",
       "legendFormat": "Objects scanned in current self heal run"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_process_cpu_total_seconds{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "CPU Usage Rate [{{server}}]"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "minio_node_process_resident_memory_bytes{pod=\"$pod\"}",
       "legendFormat": "Memory Used [{{server}}]"
      }
     ]
    },
    {
     "title": "Drive Used Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "minio_node_drive_used_bytes{pod=\"$pod\"}",
       "legendFormat": "Used Capacity [{{server}}:{{drive}}]"
      }
     ]
    },
    {
     "title": "Drives Free Inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minio_node_drive_free_inodes{pod=\"$pod\"}",
       "legendFormat": "Free Inodes [{{server}}:{{drive}}]"
      }
     ]
    },
    {
     "title": "Node Syscalls",
     "type": "timeseries",
     "description": "Number of online drives per MinIO Server",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(minio_node_syscall_read_total{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Read Syscalls [{{server}}]"
      },
      {
       "expr": "rate(minio_node_syscall_write_total{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Write Syscalls [{{server}}]"
      }
     ]
    },
    {
     "title": "Node File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minio_node_file_descriptor_open_total{pod=\"$pod\"}",
       "legendFormat": "Open FDs [{{server}}]"
      }
     ]
    },
    {
     "title": "Node IO",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(minio_node_io_rchar_bytes{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Node RChar [{{server}}]"
      },
      {
       "expr": "rate(minio_node_io_wchar_bytes{pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Node WChar [{{server}}]"
      }
     ]
    }
   ]
  }
 ]
}