{
 "title": "MongoDB Dashboard",
 "tags": [
  "DB",
  "Mongodb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "pod", "label": "Pod Name", "query": { "query": "label_values(mongodb_up,pod)" } },
   { "name": "interval", "query": "5m,10m,15m,30m,1h,6h,1d" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job!=\"node-exporter\", job=\"$dbs_pod_name\"},job)"
    }
   },
   {
    "name": "dbs_pod_name",
    "label": "dbs_pod_name",
    "query": {
     "query": "label_values(mongodb_up{pod=\"$pod\"},pod)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(mongodb_mongod_db_data_size_bytes{database!~\"admin\", database!=\"local\", database!=\"config\", pod=\"$pod\"},database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_version_info{pod=~\"$pod\"}",
       "legendFormat": "{{mongodb}}"
      }
     ]
    },
    {
     "title": "DB Data Size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_mongod_db_data_size_bytes{pod=~\"$pod\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_fsTotalSize{pod=~\"$pod\"}) - sum(mongodb_dbstats_fsUsedSize{pod=~\"$pod\", database=~\"$database\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB Collections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_mongod_db_collections_total{pod=~\"$pod\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_mongod_op_counters_total{pod=~\"$pod\",type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{pod=~\"$pod\",type!=\"command\"}[5m]) or rate(mongodb_op_counters_total{pod=~\"$pod\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{pod=~\"$pod\",type!=\"command\"}[5m]))"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{pod=~\"$pod\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{pod=~\"$pod\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{pod=~\"$pod\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{pod=~\"$pod\",type=\"command\"}[5m]) > 0))"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{pod=~\"$pod\",state=\"available\"}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{pod=~\"$pod\",state=\"current\"}"
      }
     ]
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"mongo-0\",container=~\"mongodb\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"^($node)$\"} - node_memory_MemFree_bytes{job=~\"^($node)$\"} - node_memory_Buffers_bytes{job=~\"^($node)$\"} - node_memory_Cached_bytes{job=~\"^($node)$\"} - node_memory_Slab_bytes{job=~\"^($node)$\"} - node_memory_PageTables_bytes{job=~\"^($node)$\"} - node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=~\"^($node)$\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"^($node)$\"} - node_memory_SwapFree_bytes{job=~\"^($node)$\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "container_memory_usage_bytes{container!=\"POD\", pod=\"mongo-0\", container=\"mongodb\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=\"mongo-0\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_receive_bytes_total{pod=\"mongo-0\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=\"mongo-0\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_transmit_bytes_total{pod=\"mongo-0\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    },
    {
     "expr": "rate(container_fs_reads_total{container!=\"POD\", pod=\"mongo-0\",container=\"mongodb\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Read bytes"
    },
    {
     "expr": "rate(container_fs_writes_total{container!=\"POD\", pod=\"mongo-0\",container=\"mongodb\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Writes bytes"
    }
   ]
  },
  {
   "title": "Query Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Document Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Document Query Executor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Latency Detail",
     "type": "timeseries",
     "description": "Average latency of operations (classified by read, write, or (other) command)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (service_name,type) (rate(mongodb_mongod_op_latencies_latency_total{pod=~\"$pod\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{pod=~\"$pod\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{pod=~\"$pod\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{pod=~\"$pod\"}[5m]) > 0))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Command Operations",
     "type": "timeseries",
     "description": "Ops or Replicated Ops/sec classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_total{pod=~\"$pod\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{pod=~\"$pod\", type!=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{pod=~\"$pod\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{pod=~\"$pod\", type!=\"command\"}[5m]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{pod=~\"$pod\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{pod=~\"$pod\", type!~\"(command|query|getmore)\"}[5m]) or\nrate(mongodb_mongos_op_counters_repl_total{pod=~\"$pod\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongos_op_counters_repl_total{pod=~\"$pod\", type!~\"(command|query|getmore)\"}[5m]))",
       "legendFormat": "repl_{{type}}"
      },
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_ttl_deleted_documents_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_ttl_deleted_documents_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_metrics_ttl_deleted_documents_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "ttl_delete"
      }
     ]
    },
    {
     "title": "Query Efficiency",
     "type": "timeseries",
     "description": "Ratio of Documents returned or Index entries scanned / full documents scanned",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_mongod_metrics_document_total{pod=~\"$pod\", state=\"returned\"}[$interval]))/\nsum(rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\", state=\"scanned_objects\"}[$interval])) \nor\nsum(irate(mongodb_mongod_metrics_document_total{pod=~\"$pod\", state=\"returned\"}[5m]))/\nsum(irate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\", state=\"scanned_objects\"}[5m]))",
       "legendFormat": "Document"
      },
      {
       "expr": "(sum(rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\", state=\"scanned\"}[$interval]))/\nsum(rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\", state=\"scanned_objects\"}[$interval])) \nor\nsum(irate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\", state=\"scanned\"}[5m]))/\nsum(irate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\", state=\"scanned_objects\"}[5m])))",
       "legendFormat": "Index"
      }
     ]
    },
    {
     "title": "Scanned and Moved Objects",
     "type": "timeseries",
     "description": "This panel shows the number of objects (both data (scanned_objects) and index (scanned)) as well as the number of documents that were moved to a new location due to the size of the document growing. Moved documents only apply to the MMAPv1 storage engine.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_query_executor_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{pod=~\"$pod\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "moved"
      }
     ]
    },
    {
     "title": "getLastError Write Operations",
     "type": "timeseries",
     "description": "Legacy driver operation: Number of getLastError commands that timed out trying to confirm write concern.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_get_last_error_wtime_num_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_num_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_num_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_num_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{pod=~\"$pod\"}[$interval]) or\nirate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{pod=~\"$pod\"}[$interval]) or\nirate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "getLastError Write Time",
     "type": "timeseries",
     "description": "Legacy driver operation: Number of, and Sum of time spent, per second executing getLastError commands to confirm write concern.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{pod=~\"$pod\"}[5m]))",
       "legendFormat": "Write Wait Time"
      }
     ]
    },
    {
     "title": "Assert Events",
     "type": "timeseries",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (service_name,type) (rate(mongodb_mongod_asserts_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_asserts_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_asserts_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_asserts_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "timeseries",
     "description": "Unix or Window memory page faults. Not necessarily from mongodb.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_extra_info_page_faults_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_extra_info_page_faults_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_extra_info_page_faults_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_extra_info_page_faults_total{pod=~\"$pod\"}[5m]) or\nrate(mongodb_extra_info_page_faults_total{pod=~\"$pod\"}[$interval]) or \nirate(mongodb_extra_info_page_faults_total{pod=~\"$pod\"}[5m]))",
       "legendFormat": "Faults"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk (10,irate(mongodb_top_queries_time{pod=~\"$pod\", database=~\"$database\"}[15m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Update Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk (10,irate(mongodb_top_update_time{pod=~\"$pod\", database=~\"$database\"}[15m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Remove Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk (10,irate(mongodb_top_remove_time{pod=~\"$pod\", database=~\"$database\"}[15m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Insert Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk (10,irate(mongodb_top_insert_time{pod=~\"$pod\", database=~\"$database\"}[15m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "ReadLock Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk (10,irate(mongodb_top_readLock_time{pod=~\"$pod\", database=~\"$database\"}[15m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "WriteLock Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk (10,irate(mongodb_top_writeLock_time{pod=~\"$pod\", database=~\"$database\"}[15m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    }
   ]
  }
 ]
}