{
 "title": "PostgreSQL Dashboard",
 "tags": [
  "DB",
  "Podtgres"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "5m,10m,15m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   { "name": "pod", "label": "Pod Name", "query": { "query": "label_values(pg_up,pod)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_size_bytes{pod=\"$pod\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job!=\"node-exporter\", job=\"$dbs_pod_name\"},job)"
    }
   },
   {
    "name": "dbs_pod_name",
    "label": "dbs_pod_name",
    "query": {
     "query": "label_values(pg_up{pod=\"$pod\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{pod=~\"$pod\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=~\"$pod\"} * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{pod=~\"$pod\",datname=~\"^($datname)$\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"postgres-0\",container=\"postgresql\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"^($node)$\"} - node_memory_MemFree_bytes{job=~\"^($node)$\"} - node_memory_Buffers_bytes{job=~\"^($node)$\"} - node_memory_Cached_bytes{job=~\"^($node)$\"} - node_memory_Slab_bytes{job=~\"^($node)$\"} - node_memory_PageTables_bytes{job=~\"^($node)$\"} - node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=~\"^($node)$\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"^($node)$\"} - node_memory_SwapFree_bytes{job=~\"^($node)$\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "container_memory_usage_bytes{container!=\"POD\", pod=\"postgres-0\",container=\"postgresql\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=\"postgres-0\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_receive_bytes_total{pod=\"postgres-0\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=\"postgres-0\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_transmit_bytes_total{pod=\"postgres-0\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    },
    {
     "expr": "rate(container_fs_reads_total{container!=\"POD\", pod=\"postgres-0\",container=\"postgresql\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Read bytes"
    },
    {
     "expr": "rate(container_fs_writes_total{container!=\"POD\", pod=\"postgres-0\",container=\"postgresql\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Writes bytes"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections $datname",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{datname=~\"^($datname)$\", pod=~\"^($pod)$\"}) by (datname)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "OOM Killer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_vmstat_oom_kill{job=~\"^($node)$\"}",
       "legendFormat": "oom killer invocations "
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"^($datname)$\", pod=~\"^($pod)$\", state=\"active\"} !=0",
       "legendFormat": "{{datname}}-{{application_name}}"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{pod=~\"$pod\", datname=~\"$datname\"}[15m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{pod=~\"$pod\", datname=~\"$datname\"}[15m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched{datname=~\"$datname\", pod=~\"$pod\"} [15m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_returned{datname=~\"$datname\", pod=~\"$pod\"} [15m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{pod=~\"$pod\", datname=~\"$datname\"} / (pg_stat_database_blks_read{pod=~\"$pod\", datname=~\"$datname\"} + pg_stat_database_blks_hit{pod=~\"$pod\", datname=~\"$datname\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_updated{datname=~\"$datname\", pod=~\"$pod\"} [15m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", pod=~\"$pod\", mode=~\"$mode\"} != 0",
       "legendFormat": "{{datname}},{{mode}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_deleted{datname=~\"$datname\", pod=~\"$pod\"} [15m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{datname=~\"$datname\", pod=~\"$pod\"} [15m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", pod=~\"$pod\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "timeseries",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_temp_bytes{pod=~\"$pod\", datname=~\"$datname\"} [15m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{pod=~\"$pod\", datname=~\"$datname\"} [15m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "rate(pg_stat_database_xact_rollback{pod=~\"$pod\", datname=~\"$datname\"} [15m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    }
   ]
  }
 ]
}