{
 "title": "Redis Dashboard",
 "tags": [
  "DB",
  "Redis"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "pod", "label": "pod", "query": { "query": "label_values(redis_up,pod)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job!=\"node-exporter\", job=\"$dbs_pod_name\"},job)"
    }
   },
   {
    "name": "dbs_pod_name",
    "label": "dbs_pod_name",
    "query": {
     "query": "label_values(redis_up{pod=\"$pod\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(redis_uptime_in_seconds{pod=~\"$pod\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(redis_connected_clients{pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (redis_memory_used_bytes{pod=~\"$pod\"}  / redis_memory_max_bytes{pod=~\"$pod\"}))"
      }
     ]
    },
    {
     "title": "Total Commands / sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_commands_total{pod=~\"$pod\"} [5m])) by (cmd)",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "hits, {{ instance }}"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "misses, {{ instance }}"
      }
     ]
    }
   ]
  },
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"redis-.*\",container=~\"redis|sentinel\"}[$__rate_interval])",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"^($node)$\"} - node_memory_MemFree_bytes{job=~\"^($node)$\"} - node_memory_Buffers_bytes{job=~\"^($node)$\"} - node_memory_Cached_bytes{job=~\"^($node)$\"} - node_memory_Slab_bytes{job=~\"^($node)$\"} - node_memory_PageTables_bytes{job=~\"^($node)$\"} - node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=~\"^($node)$\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"^($node)$\"} - node_memory_SwapFree_bytes{job=~\"^($node)$\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "container_memory_usage_bytes{container!=\"POD\", pod=~\"redis-.*\",container=~\"redis|sentinel\"}",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=~\"redis-.*\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_receive_bytes_total{pod=~\"redis-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=~\"redis-.*\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_transmit_bytes_total{pod=~\"redis-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    },
    {
     "expr": "rate(container_fs_reads_total{container!=\"POD\", pod=~\"redis-.*\",container=~\"redis|sentinel\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Read bytes"
    },
    {
     "expr": "rate(container_fs_writes_total{container!=\"POD\", pod=~\"redis-.*\",container=~\"redis|sentinel\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Writes bytes"
    }
   ]
  },
  {
   "title": "Redis Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_memory_used_bytes{pod=~\"$pod\"} ",
       "legendFormat": "used"
      },
      {
       "expr": "redis_memory_max_bytes{pod=~\"$pod\"} ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(redis_net_input_bytes_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "{{ input }}"
      },
      {
       "expr": "rate(redis_net_output_bytes_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "{{ output }}"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{pod=~\"$pod\"}) by (db, instance)",
       "legendFormat": "{{ db }}, {{ instance }}"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{pod=~\"$pod\"}) - sum (redis_db_keys_expiring{pod=~\"$pod\"}) ",
       "legendFormat": "not expiring"
      },
      {
       "expr": "sum (redis_db_keys_expiring{pod=~\"$pod\"}) ",
       "legendFormat": "expiring"
      }
     ]
    },
    {
     "title": "Expired/Evicted Keys",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_expired_keys_total{pod=~\"$pod\"}[5m])) by (instance)",
       "legendFormat": "expired, {{ instance }}"
      },
      {
       "expr": "sum(rate(redis_evicted_keys_total{pod=~\"$pod\"}[5m])) by (instance)",
       "legendFormat": "evicted, {{ instance }}"
      }
     ]
    },
    {
     "title": "Connected/Blocked Clients",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_connected_clients{pod=~\"$pod\"})",
       "legendFormat": "connected"
      },
      {
       "expr": "sum(redis_blocked_clients{pod=~\"$pod\"})",
       "legendFormat": "blocked"
      }
     ]
    },
    {
     "title": "Average Time Spent by Command / sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{pod=~\"$pod\"}[5m])) by (cmd)\n  /\nsum(irate(redis_commands_total{pod=~\"$pod\"}[5m])) by (cmd)\n",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Total Time Spent by Command / sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{pod=~\"$pod\"}[5m])) by (cmd) != 0",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Redis connected clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_connected_clients{pod=\"$pod\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}