apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.name" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.global.grpc_port }}
      targetPort: grpc
      protocol: TCP
    - name: http
      port: {{ .Values.global.http_port }}
      targetPort: http
      protocol: TCP
{{- if or (eq .Values.global.edition "enterprise") (not (eq .Values.global.solution "onPremise")) }}
{{- if eq (toString .Values.global.monitoring.enabled) "true" }}
    - name: http-metrics
      port: {{ .Values.global.http_metrics }}
      targetPort: http
      protocol: TCP
{{- end }}
{{- end }}
  selector:
    {{- include "todolist.selectorLabels" . | nindent 4 }}
