apiVersion: v2
appVersion: 1.16.0
description: Elma365 bpmn processor
home: https://git.elewise.com/elma365/processor
name: processor
sources:
- dreg.elewise.com:5005/elma365/processor
type: application
version: 0.1.0
