apiVersion: v1
kind: Service
metadata:
  name: {{ template "front.name" . }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-external
      port: 80
      targetPort: {{ .Values.global.http_port }}
      protocol: TCP
    - name: http
      port: {{ .Values.global.http_port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "front.selectorLabels" . | nindent 4 }}
