{{- define "helm-library.alerts" }}
{{- if or (eq .Values.global.edition "enterprise") (not (eq .Values.global.solution "onPremise")) }}
{{- if eq (toString .Values.global.monitoring.enabled) "true" }}
{{- if eq (toString .Values.global.monitoring.alerts.enabled) "true" }}
{{- if ($.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule") }}
{{- $root := .Files }}
{{- range $path, $bytes := $root.Glob "alerts/**.yaml" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    role: microservice-rules
    app: prometheus-operator
  name: prometheus-rules-{{ $path | base }}
spec:
  groups:
  - name: microservice-rules
    rules:
{{ $root.Get $path | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
