{{- define "helm-library.hpa-worker" }}
{{- $dot := required "GlobalContext should be passed" .GlobalContext }}
{{- $localContext := required "LocalContext should be passed" .LocalContext }}
{{- $name := required "Name should be passed" $localContext.name }}
{{- $autoscaling := required "Autoscaling config should be passed" $localContext.autoscaling }}
{{- $inputParams := .}}

{{- if or ( eq $dot.Values.global.edition "enterprise" ) ( not ( eq $dot.Values.global.solution "onPremise" ) ) }}
{{- if or $dot.Values.global.autoscaling.enabled $dot.Values.autoscaling.enabled }}
{{- if eq $dot.Values.global.autoscaling.type "hpa" }}
{{- $dbsExporterService := $dot.Values.global.monitoring.rmqExporterName | default "dbsexporter-rabbitmq" -}}
{{- if semverCompare "<1.23-0" (include "kubeVersion" .) }}
apiVersion: autoscaling/v2beta1
{{- else -}}
apiVersion: autoscaling/v2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  labels:
  {{- include "worker.pool.labels" $inputParams | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $autoscaling.minReplicas | default $dot.Values.global.autoscaling.minReplicas }}
  maxReplicas: {{ $autoscaling.maxReplicas | default $dot.Values.global.autoscaling.maxReplicas }}
  metrics:
    {{- if or $dot.Values.global.autoscaling.targetMemoryUtilizationPercentage $autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "kubeVersion" $) }}
        targetAverageUtilization: {{ $autoscaling.targetMemoryUtilizationPercentage | default $dot.Values.global.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ $autoscaling.targetMemoryUtilizationPercentage | default $dot.Values.global.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if or $dot.Values.global.autoscaling.targetCPUUtilizationPercentage $autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "kubeVersion" $) }}
        targetAverageUtilization: {{ $autoscaling.targetCPUUtilizationPercentage | default $dot.Values.global.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ $autoscaling.targetCPUUtilizationPercentage | default $dot.Values.global.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if eq (toString $dot.Values.global.monitoring.provisioner) "deckhouse" }}
    {{- if eq $name "worker" }}
    - type: External
      external:
        metric:
          name: elma365_worker
          selector:
            matchLabels:
              service: {{ $dbsExporterService }}
        target:
          type: Value
          value: {{ $autoscaling.rabbitmqQueueLength | default $dot.Values.global.autoscaling.rabbitmqQueueLength }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
