{{- define "helm-library.keda-worker" }}
{{- $dot := required "GlobalContext should be passed" .GlobalContext }}
{{- $localContext := required "LocalContext should be passed" .LocalContext }}
{{- $name := required "Name should be passed" $localContext.name }}
{{- $autoscaling := required "Autoscaling config should be passed" $localContext.autoscaling }}
{{- $queueName := required "QueueName should be passed" $localContext.queueName }}
{{- $inputParams := .}}

{{- if or ( eq $dot.Values.global.edition "enterprise" ) ( not ( eq $dot.Values.global.solution "onPremise" ) ) }}
{{- if or $dot.Values.global.autoscaling.enabled $dot.Values.autoscaling.enabled }}
{{- if eq $dot.Values.global.autoscaling.type "keda" }}
{{- if ($.Capabilities.APIVersions.Has "keda.sh/v1alpha1/ScaledObject") }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $name }}-trigger-auth-amqp-conn
spec:
  secretTargetRef:
    - parameter: host
      name: elma365-db-connections
      key: AMQP_URL
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $name }}
  labels:
  {{- include "worker.pool.labels" $inputParams | nindent 4 }}
spec:
  minReplicaCount: {{ $autoscaling.minReplicas | default $dot.Values.global.autoscaling.minReplicas }}
  maxReplicaCount: {{ $autoscaling.maxReplicas | default $dot.Values.global.autoscaling.maxReplicas }}
  scaleTargetRef:
    name: {{ $name }}
  triggers:
    {{- if or $dot.Values.global.autoscaling.targetMemoryUtilizationPercentage $autoscaling.targetMemoryUtilizationPercentage }}
    - type: memory
      metricType: Utilization
      metadata:
        value: {{ $autoscaling.targetMemoryUtilizationPercentage | default $dot.Values.global.autoscaling.targetMemoryUtilizationPercentage | quote }}
    {{- end }}
    {{- if or $dot.Values.global.autoscaling.targetCPUUtilizationPercentage $autoscaling.targetCPUUtilizationPercentage }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ $autoscaling.targetCPUUtilizationPercentage | default $dot.Values.global.autoscaling.targetCPUUtilizationPercentage | quote }}
    {{- end }}
    - type: rabbitmq
      metadata:
        protocol: auto
        mode: QueueLength
        value: {{ $autoscaling.rabbitmqQueueLength | default $dot.Values.global.autoscaling.rabbitmqQueueLength | quote }}
        queueName: {{ $queueName }}
      authenticationRef:
        name: {{ $name }}-trigger-auth-amqp-conn
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
