{{- define "helm-library.pdb" }}
{{- $name := include "helm-library.name" . }}

{{- $pdbEnabled := false }}
{{- if hasKey .Values "podDisruptionBudget" }}
{{- $pdbEnabled = .Values.podDisruptionBudget.enabled | default false }}
{{- else if hasKey .Values.global "podDisruptionBudget" }}
{{- $pdbEnabled = .Values.global.podDisruptionBudget.enabled | default false }}
{{- end }}

{{- if $pdbEnabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm-library.selectorLabels" . | nindent 6 }}
  {{- $hasMinAvailable := or (and (hasKey .Values "podDisruptionBudget") (hasKey .Values.podDisruptionBudget "minAvailable")) (and (hasKey .Values.global "podDisruptionBudget") (hasKey .Values.global.podDisruptionBudget "minAvailable")) }}
  {{- $hasMaxUnavailable := or (and (hasKey .Values "podDisruptionBudget") (hasKey .Values.podDisruptionBudget "maxUnavailable")) (and (hasKey .Values.global "podDisruptionBudget") (hasKey .Values.global.podDisruptionBudget "maxUnavailable")) }}
  {{- if $hasMinAvailable }}
  minAvailable: {{ if hasKey .Values "podDisruptionBudget" }}{{ .Values.podDisruptionBudget.minAvailable }}{{ else }}{{ .Values.global.podDisruptionBudget.minAvailable }}{{ end }}
  {{- else if $hasMaxUnavailable }}
  maxUnavailable: {{ if hasKey .Values "podDisruptionBudget" }}{{ .Values.podDisruptionBudget.maxUnavailable }}{{ else }}{{ .Values.global.podDisruptionBudget.maxUnavailable }}{{ end }}
  {{- else }}
  minAvailable: 1
  {{- end }}

{{- end }}
{{- end }}
