{{- define "helm-library.prometheusrules" }}
{{- if or (eq .Values.global.edition "enterprise") (not (eq .Values.global.solution "onPremise")) }}
{{- if eq (toString .Values.global.monitoring.enabled) "true" }}
{{- if eq (toString .Values.global.monitoring.alerts.enabled) "true" }}
{{- if ($.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule") }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "helm-library.fullname" . }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  {{- if .Values.metrics.prometheusRule.rules }}
  groups:
    - name: {{ template "helm-library.name" . }}
      rules: {{- toYaml .Values.metrics.prometheusRule.rules | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
