global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  holdingEnabled: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  projectxmlexport:
    livenessProbe: {}
    readinessProbe: {}
    startupProbe: {}
projectxmlexport:
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
images:
  service: ci-1bf841a3
  asposetasks: ci-32745a8e
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpTimeout: 1m
  exportGanttURL: "localhost:80"
  aspose_tasks_port: 4000
nameOverride: projects
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
autoscaling: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
logging:
  default: Information
  microsoft: Warning
annotations:
  ci.elma365.com/commit: "2ed519b1"
  ci.elma365.com/checksum: "1bf841a3"
  ci.elma365.com/job_id: "3708457"
  ci.elma365.com/timestamp: "2025-09-30T11:04:56+04:00"
  ci.elma365.com/pipeline_id: "629065"
