apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "notifier.name" . }}
  labels:
    {{- include "notifier.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "notifier.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "notifier.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.podSecurityContext" . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/notifier/notifier:{{ .Values.images.notifier }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            {{- if .Values.appconfig.push.fcmKey }}
            - name: ELMA365_FCM_CREDENTIALS_PATH
              value: {{ .Values.appconfig.push.fcmKeyPath | quote }}
            {{- end }}
            - name: ELMA365_NAMESPACE
              value: {{ default .Release.Namespace .Values.namespace }} # для редиса
            - name: ELMA365_ITEM_UPDATED_CONCURRENCY_COUNT
              value: {{ .Values.appconfig.itemUpdatedConcurrencyCount | quote }}
            - name: ELMA365_OBSERVABLE_COLLECTION_EVENTS_CONCURRENCY_COUNT
              value: {{ .Values.appconfig.observableCollectionEventsConcurrencyCount | quote }}
            - name: ELMA365_PUSH_PROTOCOL
              value: {{ .Values.appconfig.pushProtocol | quote }}
            - name: ELMA365_NOTIGATE_ENABLED
              value: {{ .Values.global.notifierV2 | quote }}
            - name: ELMA365_VAPID_PUBLIC_KEY
              value: {{ .Values.appconfig.push.vapidPublicKey | quote }}
            - name: ELMA365_VAPID_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: notifier
                  key: VAPID_PRIVATE_KEY
            - name: ELMA365_HMS_CLIENT_ID
              value: {{ .Values.appconfig.push.hmsClientId | quote }}
            - name: ELMA365_HMS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notifier
                  key: HMS_CLIENT_SECRET
            - name: ELMA365_RUSTORE_PROJECT_ID
              value: {{ .Values.appconfig.push.rustoreProjectId | quote }}
            - name: ELMA365_RUSTORE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notifier
                  key: RUSTORE_AUTH_TOKEN
          {{- if .Values.global.helmLibrary }}
            {{- include "helm-library.deployment.env" . | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
      {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.deployment.securityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.probes" . | indent 10 }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts-notifier" . | indent 10 }}
          {{- include "helm-library.deployment.lifecycle" . | indent 10 }}
        {{- include "helm-library.deployment.volumes-notifier" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
