global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
images:
  events: ci-7654f5ee
  setup: ci-228f35d1
image:
  repository: {}
  pullSecret: {}
appconfig:
  schema: public
autoscaling: {}
nameOverride: event-bus
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
service:
  type: ClusterIP
annotations:
  ci.elma365.com/commit: "6b44da18"
  ci.elma365.com/checksum: "228f35d1"
  ci.elma365.com/job_id: "3709170"
  ci.elma365.com/timestamp: "2025-09-30T11:09:09+04:00"
  ci.elma365.com/pipeline_id: "629097"
