apiVersion: v1
kind: Secret
metadata:
  name: {{ template "integrations.name" . }}
  labels:
    {{- include "integrations.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  # Ключ алгоритма шифрования AES (16, 24, или 32 байта).
  aes_crypt_key: {{ .Values.appconfig.aesCryptKey | b64enc }}
