global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {event-producer: "true"}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    rabbitmqQueueLength: 500
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
images:
  service: ci-9f6e2df8
  setup: develop
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpTimeout: 1m
autoscaling: {}
nameOverride: dup-detector
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
resourcesJobs: {}
resources:
  requests:
    memory: "300Mi"
    cpu: "50m"
  limits:
    memory: "555Mi"
    cpu: "555m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "f1af5d1e"
  ci.elma365.com/checksum: "9f6e2df8"
  ci.elma365.com/job_id: "3212742"
  ci.elma365.com/timestamp: "2025-05-06T06:33:42+00:00"
  ci.elma365.com/pipeline_id: "574580"
