- alert: balancer down
  annotations:
    title: "Instance  down"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Instance of balancer has been down for more than 3 minute.
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    up {app='balancer'} == 0
  for: 3m
  labels:
    severity: critical
- alert: Low response
  annotations:
    title: "Low response rate"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Response rate of balancer less than 95% for more than 5 minute.
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    sum(irate(response_total{app='balancer', classification='success', direction='inbound'}[1m])) 
    / sum(irate(response_total{app='balancer', direction='inbound'}[1m])) < 0.95
  for: 5m
  labels:
    severity: critical
- alert: Long latencies for event delivery
  annotations:
    title: "Long latencies for event delivery"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Long latencies for event delivery for balancer
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    histogram_quantile(0.99, sum(irate(eventbus_delivery_duration_bucket{pod=~"balancer.*"}[1m]))
    by (le, namespace, pod)) > 500
  for: 5m
  labels:
    severity: critical
- alert: balancer http request duration too high 
  annotations:
    title: "balancer http request duration too high for 5 min"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      balancer http request duration too high for 5 min
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job="balancer"}[5m])) by (le,namespace)) > 3
  for: 5m
  labels:
    severity: critical    