{{- if .Values.global.managedServices.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: babysitter-sa-binder
  namespace: {{ tpl .Values.global.managedServices.namespace . }}
subjects:
  - kind: ServiceAccount
    name: babysitter-sa
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: Role
  name: babysitter-manager
  apiGroup: ""
{{- end }}
