global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-9fa67971
  setup: ci-6d17633a
image:
  repository: {}
  pullSecret: {}
nameOverride: telemetrist
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
autoscaling: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
telemetrist:
  labels:
    app: telemetrist
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
appconfig:
  cleanupInterval: 1h
  metricCleanupThreshold: 2h
  metricStoreDuration: 24h
  reportManualTaskTimeout: 5m
  reportManualTaskStoreDuration: 10m
  traceStoreDurationSaaS: 15m
  traceStoreDurationOnPremises: 240h
  traceCleanupInterval: 15m
  traceMetadataCacheTtl: 15m
annotations:
  ci.elma365.com/commit: "3c7a85b5"
  ci.elma365.com/checksum: "6d17633a"
  ci.elma365.com/job_id: "3466718"
  ci.elma365.com/timestamp: "2025-07-15T17:52:22+04:00"
  ci.elma365.com/pipeline_id: "606880"
