{
 "title": "Infra PostgreSQL Yandex Dashboard",
 "tags": [
  "DB",
  "PostgreSQL",
  "Infra",
  "YC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "resource_id",
    "label": "Cluster",
    "query": {
     "query": "label_values({service=\"managed-postgresql\"},resource_id)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({service=\"managed-postgresql\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PostgreSQL $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "PostgreSQL CPU usage $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=~\"^($node)$\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Memory usage $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=~\"^($node)$\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk IOPS $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=~\"^($node)$\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=~\"^($node)$\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk usage on $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_used_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", node=~\"^($node)$\"}",
     "legendFormat": "Disk used"
    },
    {
     "expr": "disk_free_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", node=~\"^($node)$\"}",
     "legendFormat": "Disk free"
    }
   ]
  },
  {
   "title": "PostgreSQL OOM Count $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "oom_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\",node=~\"^($node)$\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "avg(pooler_query_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\",node=~\"^($node)$\"})",
     "legendFormat": "Statements - {{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Total pooler connections $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "sum(pooler_used_clients{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", node=~\"^($node)$\"})",
     "legendFormat": "clients"
    },
    {
     "expr": "sum(pooler_used_servers{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", node=~\"^($node)$\"})",
     "legendFormat": "servers"
    }
   ]
  }
 ]
}