{
 "title": "Infra",
 "tags": [
  "DB",
  "Infra",
  "YC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pg_resource_id",
    "label": "PostgreSQL Cluster",
    "query": {
     "query": "label_values({service=\"managed-postgresql\"},resource_id)"
    }
   },
   {
    "name": "mng_resource_id",
    "label": "MongoDB Cluster",
    "query": {
     "query": "label_values({service=\"managed-mongodb\"},resource_id)"
    }
   },
   {
    "name": "minio_resource_id",
    "label": "Minio Cluster",
    "query": {
     "query": "label_values({service=\"storage\"},resource_id)"
    }
   },
   {
    "name": "redis_resource_id",
    "label": "Redis Cluster",
    "query": {
     "query": "label_values({service=\"managed-redis\"},resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-postgresql\", resource_id=~\"^($pg_resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-postgresql\", resource_id=~\"^($pg_resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-postgresql\", resource_id=~\"^($pg_resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-postgresql\", resource_id=~\"^($pg_resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "MongoDB CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-mongodb\", resource_id=~\"^($mng_resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "MongoDB Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-mongodb\", resource_id=~\"^($mng_resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MongoDB Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-mongodb\", resource_id=~\"^($mng_resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-mongodb\", resource_id=~\"^($mng_resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Redis CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-redis\", resource_id=~\"^($redis_resource_id)$\", node=\"master\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "Redis Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-redis\", resource_id=~\"^($redis_resource_id)$\", node=\"master\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Redis Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-redis\", resource_id=~\"^($redis_resource_id)$\", node=\"master\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-redis\", resource_id=~\"^($redis_resource_id)$\", node=\"master\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Minio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Minio Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rps{service=\"storage\", method!~\"PutRequests|PostRequests|DeleteRequests\"}",
     "legendFormat": "{{resource_id}}-{{method}}"
    }
   ]
  },
  {
   "title": "Minio Modify Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rps{service=\"storage\", method=~\"PutRequests|PostRequests|DeleteRequests\"}",
     "legendFormat": "{{resource_id}}-{{method}}"
    }
   ]
  },
  {
   "title": "Minio Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "traffic{service=\"storage\", bytes=~\"BytesDownloaded|BytesUploaded\"}",
     "legendFormat": "{{resource_id}}-{{bytes}}"
    }
   ]
  }
 ]
}