{
 "title": "Minio Yandex Dashboard",
 "tags": [
  "DB",
  "Minio",
  "YC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "resource_id",
    "label": "resource_id",
    "query": {
     "query": "label_values({service=\"storage\"},resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Minio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Minio Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rps{service=\"storage\", method!~\"PutRequests|PostRequests|DeleteRequests\", resource_id=~\"^($resource_id)$\"}",
     "legendFormat": "{{resource_id}}-{{method}}"
    }
   ]
  },
  {
   "title": "Minio Modify Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rps{service=\"storage\", method=~\"PutRequests|PostRequests|DeleteRequests\", resource_id=~\"^($resource_id)$\"}",
     "legendFormat": "{{resource_id}}-{{method}}"
    }
   ]
  },
  {
   "title": "Minio Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "traffic{service=\"storage\", bytes=~\"BytesDownloaded|BytesUploaded\", resource_id=~\"^($resource_id)$\"}",
     "legendFormat": "{{resource_id}}-{{bytes}}"
    }
   ]
  },
  {
   "title": "Minio Objects counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "objects_count{service=\"storage\", resource_id=~\"^($resource_id)$\"}",
     "legendFormat": "{{resource_id}}-{{object_type}}"
    }
   ]
  },
  {
   "title": "Minio Space by object type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "space_usage{service=\"storage\", storage_type!~\"IceStorage|StandardStorage|ColdStorage|All\", resource_id=~\"^($resource_id)$\"}",
     "legendFormat": "{{object_type}}"
    }
   ]
  },
  {
   "title": "Minio Space by storage type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "space_usage{service=\"storage\", storage_type=~\"StandardStorage|ColdStorage|IceStorage\", resource_id=~\"^($resource_id)$\"}",
     "legendFormat": "{{storage_type}}"
    }
   ]
  }
 ]
}