{
 "title": "MongoDB Yandex Dashboard",
 "tags": [
  "DB",
  "Mongodb",
  "YC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "resource_id",
    "label": "Cluster",
    "query": {
     "query": "label_values({service=\"managed-mongodb\"},resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB CPU usage primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "MongoDB Memory usage primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MongoDB Disk IOPS primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "MongoDB secondary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB CPU usage secondary",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{__name__=~\"cpu.*\", service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\", systag!=\"\"}",
       "legendFormat": "{{systag}}"
      }
     ]
    },
    {
     "title": "MongoDB Memory usage secondary",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"mem.*\", service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\", systag!=\"\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "MongoDB Disk IOPS secondary",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "io_disk1_read_count{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
       "legendFormat": "read"
      },
      {
       "expr": "io_disk1_write_count{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MongoDB Queries on primary",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "server_status_admin_opcounters_command_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "command_rate"
    },
    {
     "expr": "server_status_admin_opcounters_getmore_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "getmore_rate"
    },
    {
     "expr": "server_status_admin_opcounters_query_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "query_rate"
    },
    {
     "expr": "server_status_admin_opcounters_update_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "update_rate"
    },
    {
     "expr": "server_status_admin_opcounters_insert_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "insert_rate"
    },
    {
     "expr": "server_status_admin_opcounters_delete_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "delete_rate"
    }
   ]
  },
  {
   "title": "MongoDB Queries on secondary",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "server_status_admin_opcounters_command_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
     "legendFormat": "command_rate"
    },
    {
     "expr": "server_status_admin_opcounters_getmore_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
     "legendFormat": "getmore_rate"
    },
    {
     "expr": "server_status_admin_opcounters_query_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
     "legendFormat": "query_rate"
    },
    {
     "expr": "server_status_admin_opcounters_update_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
     "legendFormat": "update_rate"
    },
    {
     "expr": "server_status_admin_opcounters_insert_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
     "legendFormat": "insert_rate"
    },
    {
     "expr": "server_status_admin_opcounters_delete_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", node=\"secondary\", resource_type=\"cluster\"}",
     "legendFormat": "delete_rate"
    }
   ]
  },
  {
   "title": "MongoDB Average operations time on primary",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expression": "$A / 1000 /$B", "type": "math" },
    { "expression": "$C / 1000 /$D", "type": "math" },
    { "expression": "$E / 1000 /$F", "type": "math" },
    { "expression": "$I / 1000 /$J", "type": "math" }
   ]
  },
  {
   "title": "MongoDB Average operations time on secondaries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expression": "$A / 1000 /$B", "type": "math" },
    { "expression": "$C / 1000 /$D", "type": "math" },
    { "expression": "$E / 1000 /$F", "type": "math" },
    { "expression": "$I / 1000 /$J", "type": "math" }
   ]
  },
  {
   "title": "MongoDB Write operations count, top 5 collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "topk(5, top_writeLock_time_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "MongoDB Read operations count, top 5 collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, top_readLock_time_rate{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "MongoDB Network usage per host, top 5 hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, net_bytes_recv{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "{{host}} - recv"
    },
    {
     "expr": "topk(5, net_bytes_sent{service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "{{host}} - sent"
    }
   ]
  },
  {
   "title": "MongoDB Disk read/write per host, top 5 hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(5, {__name__=~\"io.*.read_bytes\", service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "{{host}} - read"
    },
    {
     "expr": "topk(5, {__name__=~\"io.*.write_bytes\", service=\"managed-mongodb\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "{{host}} - wtite"
    }
   ]
  }
 ]
}