{
 "title": "PostgreSQL Yandex Dashboard",
 "tags": [
  "DB",
  "PostgreSQL",
  "YC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "resource_id",
    "label": "Cluster",
    "query": {
     "query": "label_values({service=\"managed-postgresql\"},resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL CPU usage primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Memory usage primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk IOPS primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"primary\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "PostgreSQL replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL CPU usage replica",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{__name__=~\"cpu.*\", service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\", systag!=\"\"}",
       "legendFormat": "{{systag}}"
      }
     ]
    },
    {
     "title": "PostgreSQL Memory usage replica",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"mem.*\", service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\", systag!=\"\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "PostgreSQL Disk IOPS replica",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "io_disk1_read_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\"}",
       "legendFormat": "read"
      },
      {
       "expr": "io_disk1_write_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\"}",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PostgreSQL Transactions/statements per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg(pooler_xact_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "Transactions - {{host}}"
    },
    {
     "expr": "avg(pooler_query_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "Statements - {{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL OOM Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "oom_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Statement quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(pooler_query_0_999{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "99.9% - {{host}}"
    },
    {
     "expr": "max(pooler_query_0_99{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "99% - {{host}}"
    },
    {
     "expr": "max(pooler_query_0_9{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "90% - {{host}}"
    },
    {
     "expr": "max(pooler_query_0_75{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "75% - {{host}}"
    },
    {
     "expr": "max(pooler_query_0_5{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "50% - {{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Sessions read bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, pg_backend_read_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", backend_type=\"client_backend\"})",
     "legendFormat": "{{backend_type}}-{{user}}-{{database}}"
    },
    {
     "expr": "topk(5, pg_backend_read_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", backend_type!=\"client_backend\"})",
     "legendFormat": "{{backend_type}}-{{user}}-{{database}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Average transaction/statement time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pooler_avg_xact_time{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "Transactions - {{host}}"
    },
    {
     "expr": "pooler_avg_query_time{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "Statements - {{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Total pooler connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "sum(pooler_used_clients{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "clients"
    },
    {
     "expr": "sum(pooler_used_servers{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "servers"
    }
   ]
  },
  {
   "title": "PostgreSQL Log Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "postgres_log_errors{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "Log Errors"
    }
   ]
  },
  {
   "title": "PostgreSQL Sessions write bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, pg_backend_write_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", backend_type=\"client_backend\"})",
     "legendFormat": "{{backend_type}}-{{user}}-{{database}}"
    },
    {
     "expr": "topk(5, pg_backend_write_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", backend_type!=\"client_backend\"})",
     "legendFormat": "{{backend_type}}-{{user}}-{{database}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk read/write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(io_disk1_read_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(io_disk1_write_count{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "PostgreSQL Replication lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "postgres_replication_lag{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Total size of WAL files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(disk_wal_size{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "WAL size"
    }
   ]
  },
  {
   "title": "PostgreSQL TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pcs/s" } },
   "targets": [
    {
     "expr": "sum(pooler_total_tcp_connections{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "tcp_connections"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk usage on primary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_used_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "Disk used"
    },
    {
     "expr": "disk_free_bytes{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "Disk free"
    }
   ]
  },
  {
   "title": "PostgreSQL Network received/sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(net_bytes_recv{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(net_bytes_sent{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"})",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "PostgreSQL Disk usage by DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "_pg_database_size{service=\"managed-postgresql\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{dbname}}"
    }
   ]
  }
 ]
}