{
 "title": "RabbitMQ Dashboard",
 "tags": [
  "DB",
  "Rabbitmq"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(rabbitmq_running,pod)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job!=\"node-exporter\", job=\"$dbs_pod_name\"},job)"
    }
   },
   {
    "name": "dbs_pod_name",
    "label": "dbs_pod_name",
    "query": {
     "query": "label_values(rabbitmq_up{pod=\"$pod\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queues",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_queuesTotal{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Consumers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_consumersTotal{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_connectionsTotal{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Channels",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_channelsTotal{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Incoming messages / s",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_queue_messages_published_total{pod=\"$pod\"}[15m]))"
      }
     ]
    },
    {
     "title": "Outgoing messages / s",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_queue_messages_delivered_total{pod=\"$pod\"}[15m]))"
      }
     ]
    },
    {
     "title": "Ready messages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Unack messages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_unacknowledged{pod=\"$pod\"})"
      }
     ]
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=~\"^($node)$\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"^($node)$\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"rabbitmq-.*\",container=\"rabbitmq\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"^($node)$\"} - node_memory_MemFree_bytes{job=~\"^($node)$\"} - node_memory_Buffers_bytes{job=~\"^($node)$\"} - node_memory_Cached_bytes{job=~\"^($node)$\"} - node_memory_Slab_bytes{job=~\"^($node)$\"} - node_memory_PageTables_bytes{job=~\"^($node)$\"} - node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=~\"^($node)$\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"^($node)$\"} - node_memory_SwapFree_bytes{job=~\"^($node)$\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{job=~\"^($node)$\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "container_memory_usage_bytes{container!=\"POD\", pod=~\"rabbitmq-.*\",container=\"rabbitmq\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"^($node)$\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=~\"rabbitmq-.*\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_receive_bytes_total{pod=~\"rabbitmq-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "# Select Pods with hostNetwork: false.\r\nkube_pod_info{host_network=\"false\", pod=~\"rabbitmq-.*\"}\r\n* on(pod)\r\n# Sum data rate for all interfaces in the Pod.\r\nsum by(pod) (rate(container_network_transmit_bytes_total{pod=~\"rabbitmq-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"^($node)$\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    },
    {
     "expr": "rate(container_fs_reads_total{container!=\"POD\", pod=~\"rabbitmq-.*\",container=\"rabbitmq\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Read bytes"
    },
    {
     "expr": "rate(container_fs_writes_total{container!=\"POD\", pod=~\"rabbitmq-.*\",container=\"rabbitmq\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}} {{device}} - Writes bytes"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "List nodes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rabbitmq_running{pod=\"$pod\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rabbitmq_node_mem_used{pod=\"$pod\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rabbitmq_node_mem_limit{pod=\"$pod\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rabbitmq_node_disk_free{pod=\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk space available before publishers blocked",
     "type": "timeseries",
     "description": "This metric is reported for the partition where the RabbitMQ data directory is stored.\n\nIf the value is zero or less, the disk alarm will be triggered and all publishing connections across all cluster nodes will be blocked.\n\nThis value can temporarily go negative because the free disk space alarm is triggered with a slight delay.\n\n* [Alarms](https://www.rabbitmq.com/alarms.html)\n* [Disk Space Alarms](https://www.rabbitmq.com/disk-alarms.html)\n* [Disk Space](https://www.rabbitmq.com/production-checklist.html#resource-limits-disk-space)\n* [Persistence Configuration](https://www.rabbitmq.com/persistence-conf.html)\n* [Blocked Connection Notifications](https://www.rabbitmq.com/connection-blocked.html)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(rabbitmq_node_disk_free * rabbitmq_running{pod=\"$pod\"}) -\r\n(rabbitmq_node_disk_free_limit * rabbitmq_running{pod=\"$pod\"})\r\n",
       "legendFormat": "Free disk space"
      }
     ]
    },
    {
     "title": "Memory available before publishers blocked",
     "type": "timeseries",
     "description": "If the value is zero or less, the memory alarm will be triggered and all publishing connections across all cluster nodes will be blocked.\n\nThis value can temporarily go negative because the memory alarm is triggered with a slight delay.\n\nThe kernel's view of the amount of memory used by the node can differ from what the node itself can observe. This means that this value can be negative for a sustained period of time.\n\nBy default nodes use resident set size (RSS) to compute how much memory they use. This strategy can be changed (see the guides below).\n\n* [Alarms](https://www.rabbitmq.com/alarms.html)\n* [Memory Alarms](https://www.rabbitmq.com/memory.html)\n* [Reasoning About Memory Use](https://www.rabbitmq.com/memory-use.html)\n* [Blocked Connection Notifications](https://www.rabbitmq.com/connection-blocked.html)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(rabbitmq_node_mem_limit * rabbitmq_running{pod=\"$pod\"}) -\n(rabbitmq_node_mem_used * rabbitmq_running{pod=\"$pod\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rabbitmq_node_mem_used{pod=\"$pod\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "TCP sockets available",
     "type": "timeseries",
     "description": "When this value reaches zero, new connections will not be accepted.\n\nClient libraries, peer nodes and CLI tools will not be able to connect when the node runs out of available file descriptors.\n\n* [Networking and RabbitMQ](https://www.rabbitmq.com/networking.html)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(rabbitmq_sockets_total * rabbitmq_running{pod=\"$pod\"}) -\n(rabbitmq_sockets_used * rabbitmq_running{pod=\"$pod\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File descriptors available",
     "type": "timeseries",
     "description": "When this value reaches zero, new connections will not be accepted and disk write operations may fail.\n\nClient libraries, peer nodes and CLI tools will not be able to connect when the node runs out of available file descriptors.\n\n* [Open File Handles Limit](https://www.rabbitmq.com/production-checklist.html#resource-limits-file-handle-limit)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(rabbitmq_fd_total * rabbitmq_running{pod=\"$pod\"}) -\n(rabbitmq_fd_used * rabbitmq_running{pod=\"$pod\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages per Queue",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages{pod=\"$pod\"}",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Messages ready to be delivered to consumers",
     "type": "timeseries",
     "description": "Total number of ready messages ready to be delivered to consumers.\n\nAim to keep this value as low as possible. RabbitMQ behaves best when messages are flowing through it. It's OK for publishers to occasionally outpace consumers, but the expectation is that consumers will eventually process all ready messages.\n\nIf this metric keeps increasing, your system will eventually run out of memory and/or disk space. Consider using TTL or Queue Length Limit to prevent unbounded message growth.\n\n* [Queues](https://www.rabbitmq.com/queues.html)\n* [Consumers](https://www.rabbitmq.com/consumers.html)\n* [Queue Length Limit](https://www.rabbitmq.com/maxlength.html)\n* [Time-To-Live and Expiration](https://www.rabbitmq.com/ttl.html)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready{pod=\"$pod\"}) by(queue)",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Rabbitmq Slow Queue Consuming",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "time() - rabbitmq_queue_head_message_timestamp{pod=~\"$pod\"} > 60",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Messages pending consumer acknowledgement",
     "type": "timeseries",
     "description": "The total number of messages that are either in-flight to consumers, currently being processed by consumers or simply waiting for the consumer acknowledgements to be processed by the queue. Until the queue processes the message acknowledgement, the message will remain unacknowledged.\n\n* [Queues](https://www.rabbitmq.com/queues.html)\n* [Confirms and Acknowledgements](https://www.rabbitmq.com/confirms.html)\n* [Consumer Prefetch](https://www.rabbitmq.com/consumer-prefetch.html)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_unacknowledged{pod=\"$pod\"}) by(queue)",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  }
 ]
}