{
 "title": "Redis Yandex Dashboard",
 "tags": [
  "DB",
  "Redis",
  "YC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "resource_id",
    "label": "Cluster",
    "query": {
     "query": "label_values({service=\"managed-redis\"},resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Redis master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis CPU usage master",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"cpu.*\", service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"master\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{systag}}"
    }
   ]
  },
  {
   "title": "Redis Memory usage master",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"mem.*\", service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"master\", resource_type=\"cluster\", systag!=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Redis Disk IOPS master",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "io_disk1_read_count{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"master\", resource_type=\"cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "io_disk1_write_count{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"master\", resource_type=\"cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Redis replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis CPU usage replica",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{__name__=~\"cpu.*\", service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\", systag!=\"\"}",
       "legendFormat": "{{systag}}"
      }
     ]
    },
    {
     "title": "Redis Memory usage replica",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"mem.*\", service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\", systag!=\"\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Redis Disk IOPS replica",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "io_disk1_read_count{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\"}",
       "legendFormat": "read"
      },
      {
       "expr": "io_disk1_write_count{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", node=\"replica\", resource_type=\"cluster\"}",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Commands Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pcs/s" } },
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis DB keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_dbsize{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Outer memory limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_used_memory_rss{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "redis_memory_limit{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Inner Memory limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_used_memory{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "redis_maxmemory{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Evicted keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_evicted_keys{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Replication buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_size{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "redis_repl_backlog_histlen{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Client recent max output buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_client_output_normal_hard{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "redis_client_output_normal_soft{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "redis_client_recent_max_output_buffer{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Client recent max input buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_client_recent_max_input_buffer{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Slowlog top operations on Master",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "slowlog_top{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", node=\"master\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Redis Slowlog top operations on Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "slowlog_top{service=\"managed-redis\", resource_id=~\"^($resource_id)$\", resource_type=\"cluster\", node=\"replica\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}