{{- if .Values.global.managedServices.watchableConfigMap.enabled }}
{{- if le (len (lookup "v1" "ConfigMap" .Values.global.managedServices.namespace .Values.global.managedServices.watchableConfigMap.name)) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.managedServices.namespace }}
  name: {{ .Values.global.managedServices.watchableConfigMap.name }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  global: |
    {{- with .Values.global.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.global.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}