{{- if eq (toString .Values.global.nodeExporter.enabled) "true" }}
{{- $out := . -}}
{{- range $val := .Values.instances }}
{{- with $out -}}
{{- if not (regexMatch ".svc.cluster.local" $val.redisAddress) }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config-{{ $val.name }}
  namespace: {{ .Release.Namespace }}
{{- if eq (toString .Values.global.provisioner) "deckhouse" }}
  labels:
    prometheus: main
{{- end }}
spec:
  honorLabels: true
  staticConfigs:
    - labels:
        job: redis-{{ $val.name }}
      targets:
        - {{ if contains "@" $val.redisAddress }}{{ (split ":" (split "@" ( $val.redisAddress | replace "redis://" ""))._1)._0  }}{{ else }}{{ (split ":" ( $val.redisAddress | replace "redis://" ""))._0 }}{{ end }}:{{ .Values.global.nodeExporter.port }}
{{- if .Values.global.relabelings }}
  relabelings:
  - targetLabel: dbsexporter
    replacement: redis
{{ toYaml .Values.global.relabelings | nindent 2 }}
{{- else }}
  relabelings:
  - regex: endpoint|namespace|pod|service
    action: labeldrop
  - targetLabel: dbsexporter
    replacement: redis
{{- end }}
  metricsPath: '/metrics'
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
