{{- if .Values.insertDefaults -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-vahter-defauts
  labels:
    {{- include "vahter.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        linkerd.io/inject: disabled
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.job.podSecurityContext" . | nindent 8 }}
      {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
      imagePullSecrets:
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
      containers:
        - name: vahter-elma-auth-defaults
          image: "{{ .Values.global.image.repository }}/docker/databases/mongodb:3.6.23-debian-9-r181"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["mongoimport", "--uri", "$(VAHTER_MONGO_URL)", "-c", "elma_auth", "--jsonArray", "/etc/defaults/elma_auth.json"]
          volumeMounts:
            - name: vahter-defaults-json-volume
              mountPath: /etc/defaults
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: VAHTER_MONGO_URL
                  optional: true
        {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.job.securityContext" . | nindent 12 }}
          {{- include "helm-library.job.resources" . | indent 10 }}
        {{- end }}
        - name: vahter-companies-defaults
          image: "{{ .Values.global.image.repository }}/docker/databases/mongodb:3.6.23-debian-9-r181"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["mongoimport", "--uri", "$(VAHTER_MONGO_URL)", "-c", "companies", "--jsonArray", "/etc/defaults/companies.json"]
          volumeMounts:
              - name: vahter-defaults-json-volume
                mountPath: /etc/defaults
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: VAHTER_MONGO_URL
                  optional: true
        {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.job.securityContext" . | nindent 12 }}
          {{- include "helm-library.job.resources" . | indent 10 }}
        {{- end }}
      volumes:
        - name: vahter-defaults-json-volume
          configMap:
            name: vahter-defaults
      restartPolicy: Never
{{- end }}
