{{- $oldTokenExpiryISO := .Values.secrets.renewToken.oldTokenExpiry | toDate "2006-01-02" }}
{{- $oldTokenExpiry := $oldTokenExpiryISO.Unix | int }}
{{- $nowTimestampISO := now.Format "2006-01-02T00:00:00Z" | toDate "2006-01-02T00:00:00Z" }}
{{- $nowTimestamp := $nowTimestampISO.Unix | int }}
{{- if eq (toString .Values.secrets.renewToken.enabled) "true" }}
{{- if and ( not ( eq .Values.secrets.renewToken.keyNew "" )) ( not ( eq .Values.secrets.renewToken.certNew  "" )) }}
{{- if le $nowTimestamp $oldTokenExpiry }}
{{- $serviceName := include "vahter.name" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-internal-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceName }}-manager-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceName }}-manager-binding
subjects:
  - kind: ServiceAccount
    name: {{ $serviceName }}-internal-kubectl
roleRef:
  kind: Role
  name: {{ $serviceName }}-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
