apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "babysitter.name" . }}
  labels:
    {{- include "babysitter.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ if or (kindIs "float64" .Values.replicaCount) (kindIs "int64" .Values.replicaCount) }}{{ .Values.replicaCount }}{{ else }}{{ .Values.global.replicaCount }}{{ end }}
  {{ end }}
  selector:
    matchLabels:
      {{- include "babysitter.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "babysitter.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.podSecurityContext" . | nindent 8 }}
      {{- end }}
      serviceAccountName: babysitter-sa
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/babysitter/service:{{ .Values.images.service }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ELMA365_BABYSITTER_K8S_MANAGEABLENAMESPACE
              value: {{ tpl .Values.global.managedServices.namespace . | quote }}
            - name: ELMA365_BABYSITTER_K8S_DEFAULTSTORAGECLASS
              value: {{ tpl .Values.global.managedServices.defaultStorageClass . | quote }}
            - name: ELMA365_BABYSITTER_SIDECAR_MONITOR_IMAGE
              value: "{{ .Values.global.image.repository }}/elma365/babysitter/monitor:{{ .Values.images.monitor }}"
            - name: ELMA365_BABYSITTER_SIDECAR_MONITOR_PORT
              value: {{ .Values.sidecar.port | quote }}
            - name: ELMA365_BABYSITTER_SIDECAR_MONITOR_PULL_SECRET
              value: {{ .Values.sidecar.pullSecret | quote }}
            - name: ELMA365_BABYSITTER_STORAGE_USAGE_THRESHOLD
              value: {{ .Values.storage.usageThreshold | quote }}
            - name: ELMA365_BABYSITTER_STORAGE_EXPAND_MULTIPLIER
              value: {{ .Values.storage.expandMultiplier | quote }}
            - name: ELMA365_BABYSITTER_STORAGE_DEFAULT_SIZE
              value: {{ .Values.storage.defaultSize | quote }}
            - name: ELMA365_BABYSITTER_STORAGE_EXPAND_PERIOD
              value: {{ .Values.storage.expandPeriod | quote }}
            - name: ELMA365_BABYSITTER_STORAGE_EXPAND_TIMEOUT
              value: {{ .Values.storage.expandTimeout | quote }}
            - name: ELMA365_BABYSITTER_STORAGE_EXPAND_CONCURRENCY
              value: {{ .Values.storage.storageExpandConcurrency | quote }}
            - name: ELMA365_BABYSITTER_ENABLE_CONFIGMAP_WATCHER
              value: {{ .Values.global.managedServices.watchableConfigMap.enabled | quote }}
            - name: ELMA365_BABYSITTER_DEFAULT_WATCHABLE_CONFIG_MAP_NAME
              value: {{ .Values.global.managedServices.watchableConfigMap.name | quote }}
          {{- if .Values.global.helmLibrary }}
            {{- include "helm-library.deployment.env" . | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
      {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.deployment.securityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.probes" . | indent 10 }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts" . | indent 10 }}
          {{- include "helm-library.deployment.lifecycle" . | indent 10 }}
        {{- include "helm-library.deployment.volumes" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
