{{- if eq .Values.global.solution "saas" -}}
{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
data:
  auth: {{ (print "apiuser:{PLAIN}" (index .Values.ingress.password)) | b64enc | quote }}
metadata:
  name: ingress-settings-password
{{- end }}
{{- end }}
