apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vahter.name" . }}
  labels:
   {{- include "vahter.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ if or (kindIs "float64" .Values.replicaCount) (kindIs "int64" .Values.replicaCount) }}{{ .Values.replicaCount }}{{ else }}{{ .Values.global.replicaCount }}{{ end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vahter.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "vahter.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include "vahter.jwtSecretChecksum" . | quote }}
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.podSecurityContext" . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/vahter/vahter:{{ .Values.images.vahter }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ELMA365_NAMESPACE
              value: {{ default .Release.Namespace .Values.namespace }} # для редиса
            - name: ELMA365_VAHTER_ALLOW_INSECURE_COOKIE
              value: {{ .Values.appconfig.allowInsecureCookie | quote }}
            - name: ELMA365_VAHTER_EASY_AUTH_TOKEN_TTL
              value: {{ .Values.appconfig.easyAuthTokenTTL }}
            - name: ELMA365_CORS_ALLOWED_HOSTS
              value: {{ join "," (pluck .Values.global.env .Values.appconfig.corsHosts | first | default .Values.appconfig.corsHosts._default ) | quote }}
            - name: ELMA365_VAHTER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: vahter-jwt
                  key: tls.key
            - name: ELMA365_VAHTER_NEW_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: vahter-jwt
                  key: tls_new.key
                  optional: true
            - name: ELMA365_VAHTER_JWT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: vahter-jwt
                  key: tls.crt
            - name: ELMA365_VAHTER_NEW_JWT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: vahter-jwt
                  key: tls_new.crt
                  optional: true
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: VAHTER_MONGO_URL
                  optional: true
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: REDIS_URL
                  optional: true
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: AMQP_URL
                  optional: true
            - name: ELMA365_MIGRATION_COLLECTION_PREFIX
              value: {{ .Values.mongodb.migrationCollectionPrefix }}
            - name: ELMA365_COLLECTION_NAME_PREFIX
              value: {{ .Values.mongodb.collectionNamePrefix | quote }}
            - name: ELMA365_APPEND_SERVICE_NAME_TO_PREFIX
              value: {{ .Values.mongodb.appendServiceNameToPrefix | quote }}
            - name: ELMA365_VAHTER_SECOND_FACTOR_MAX_FAILS_COUNT
              value: {{ .Values.appconfig.secondFactor.limitAttempts | quote }}
            - name: ELMA365_VAHTER_SECOND_FACTOR_CODE_LENGTH
              value: {{ .Values.appconfig.secondFactor.codeLength | quote }}
            - name: ELMA365_VAHTER_SECOND_FACTOR_CODE_LIFETIME
              value: {{ .Values.appconfig.secondFactor.codeLifetime | quote }}
            - name: ELMA365_VAHTER_SECOND_FACTOR_EXCLUDED_IP_NETS
              value: {{ .Values.appconfig.secondFactor.excludedIPNets | quote }}
            - name: ELMA365_VAHTER_VERIFICATION_PROVIDER_TEST_CODE
              value: {{ .Values.appconfig.verificationProvider.testCode | quote }}
            - name: ELMA365_VAHTER_EXTENDED_AUTH_CODE_TTL
              value: {{ .Values.appconfig.extendedAuth.codeTTL | quote  }}
            - name: ELMA365_VAHTER_EXTENDED_AUTH_MAX_FAILS_COUNT
              value: {{ .Values.appconfig.extendedAuth.maxFailsCount | quote  }}
            #
            # Устаревшие параметры
            # Используются в onpremise. Выпилить после обновления onpremise.
            #
            - name: MONGO_DB_NAME
              value: {{ .Values.mongodb.dbName | quote }}
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: ELMA365_MONGO_USER
                  optional: true
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elma365-db-connections
                  key: ELMA365_MONGO_PASSWORD
                  optional: true
          {{- if .Values.global.helmLibrary }}
            {{- include "helm-library.deployment.env" . | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
      {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.deployment.securityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.probes" . | indent 10 }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts" . | indent 10 }}
          {{- include "helm-library.deployment.lifecycle" . | indent 10 }}
        {{- include "helm-library.deployment.volumes" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
