global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
appconfig:
  featureFlags:
    ELMA365_FEATURE_FLAGS_ALLOW_PRIVATE_ROUTES_ACCESS: false
  saasEnabledFeatureFlags:
  onPremiseEnabledFeatureFlags:
    - delegatedEventHandling
    - appItemViewEventEnabled
    - fileDownloadEventEnabled
    - filePreviewEventEnabled
    - enableModuleServices
    - allowServerScriptsImport
    - enablePeriodicEvents
    - allowImportPortalUsersForAD
    - allowImportPortalUsersForLDAP
    - allowAuthPortalUsersWithSAML
    - allowEntityLocalization
    - enableDuplicateFTS
    - enableSQLPerformanceReport
    - enableInternalTelemetry
    - enableConvertPDFA1A
    - disableElementActivitiesStorageLimits
    - allowExternalApplicationsOIDC
    - allowScriptImportsDependencies
    - enableNewCrmTasks
    - enableAMQPStartProcess
    - collector_enable_equivalentYoE
  onPremiseCustomEnabledFeatureFlags: []
images:
  service: ci-aeefad57
image:
  repository: {}
  pullSecret: {}
ingress:
  enabled: false
  password: ''
  annotations: {}
nameOverride: settings
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "512Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "500m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "8868121a"
  ci.elma365.com/checksum: "aeefad57"
  ci.elma365.com/job_id: "3709564"
  ci.elma365.com/timestamp: "2025-09-30T10:55:56+04:00"
  ci.elma365.com/pipeline_id: "629127"
