{{- define "helm-library.deployment.lifecycle" }}
{{- if .Values.lifecycle }}
lifecycle:
  {{- toYaml .Values.lifecycle | nindent 2 }}
{{- else if .Values.global.lifecycle }}
lifecycle:
  {{- toYaml .Values.global.lifecycle | nindent 2 }}
{{- else }}
{{- if .Values.global.terminationGracePeriodSeconds }}
lifecycle:
  preStop:
    exec:
      command:
        - /bin/sleep
        - {{ mulf (.Values.global.terminationGracePeriodSeconds | default 30) 0.5 | int64 | quote }}
{{- end }}
{{- end }}
{{- end }}
