{{- define "helm-library.deployment.resources" }}
{{- if or .Values.global.autoscaling.enabled .Values.autoscaling.enabled .Values.global.resourceLimits }}
resources:
  {{- if ne (len .Values.resources) 0 -}}
  {{- toYaml .Values.resources | nindent 2 -}}
  {{- else -}}
  {{- toYaml .Values.global.resources | nindent 2 -}}
  {{- end }}
{{- end }}
{{- end }}


{{- define "helm-library.deployment.resources-gotenberg" }}
{{- if or .Values.global.autoscaling.enabled .Values.autoscaling.enabled .Values.global.resourceLimits }}
resources:
  {{- if ne (len .Values.gotenberg.resources) 0 -}}
  {{- toYaml .Values.gotenberg.resources | nindent 2 -}}
  {{- else -}}
  {{- toYaml .Values.global.resources | nindent 2 -}}
  {{- end }}
{{- end }}
{{- end }}
 

{{- define "helm-library.deployment.resources-dottemplater" }}
{{- if or .Values.global.autoscaling.enabled .Values.autoscaling.enabled .Values.global.resourceLimits }}
resources:
  {{- if ne (len .Values.dottemplater.resources) 0 -}}
  {{- toYaml .Values.dottemplater.resources | nindent 2 -}}
  {{- else -}}
  {{- toYaml .Values.global.resources | nindent 2 -}}
  {{- end }}  
{{- end }}
{{- end }}


{{- define "helm-library.deployment.resources-worker-gateway" }}
{{- if or .Values.global.autoscaling.enabled .Values.gatewayautoscaling.enabled .Values.global.resourceLimits }}
resources:
  {{- if ne (len .Values.gatewayresources) 0 -}}
  {{- toYaml .Values.gatewayresources | nindent 2 -}}
  {{- else -}}
  {{- toYaml .Values.global.resources | nindent 2 -}}
  {{- end }} 
{{- end }}  
{{- end }}
