{{- define "helm-library.deployment.scheduling" }}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- with .Values.global.nodeSelector }}
nodeSelector:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.global.tolerations }}
tolerations:
{{- toYaml . | nindent 2 }}
{{- end }}
affinity:
{{- with $.Values.global.affinity }}
{{- toYaml . | nindent 2 }}
{{- else }}
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ $name }}
              - key: release
                operator: In
                values:
                  - "{{ .Release.Name }}"
          topologyKey: kubernetes.io/hostname
        weight: 10
{{- end }}
topologySpreadConstraints:
{{- if .Values.global.topologySpreadConstraints }}
  {{- range .Values.global.topologySpreadConstraints }}
    {{- $item := merge . (dict "labelSelector" (dict "matchLabels" (dict "app" $name))) }}
    {{- printf "- %s" (toYaml $item | indent 2 | trim) | nindent 2 }}
  {{- end }}
{{- else }}
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: {{ $name }}
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: {{ $name }}
{{- end }}
{{- end }}
