global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  cronStartingDeadlineSeconds: ""
  cronTtlSecondsAfterFinished: ""
  cronActiveDeadlineSeconds: ""
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-3f05a15c
  setup: develop
image:
  repository: {}
  pullSecret: {}
nameOverride: orgunit
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "384Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
orgunit:
  labels:
    app: orgunit
annotations:
  ci.elma365.com/commit: "9da3f569"
  ci.elma365.com/checksum: "3f05a15c"
  ci.elma365.com/job_id: "3554820"
  ci.elma365.com/timestamp: "2025-08-18T16:03:27+04:00"
  ci.elma365.com/pipeline_id: "616030"
