{{- $releaseName := .Release.Name }}
{{- $name := include "telemetrist.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "telemetrist.name" . }}
  labels:
    {{- include "telemetrist.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ int (default .Values.global.replicaCount .Values.replicaCount) }}
  {{ end }}
  selector:
    matchLabels:
      {{- include "telemetrist.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "telemetrist.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.podSecurityContext" . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/telemetrist/service:{{ .Values.images.service }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: ELMA365_TELEMETRIST_METRIC_CLEANUP_INTERVAL
              value: {{ .Values.appconfig.cleanupInterval | default "1h" | quote }}
            - name: ELMA365_TELEMETRIST_METRIC_CLEANUP_THRESHOLD
              value: {{ .Values.appconfig.metricCleanupThreshold | default "2h" | quote }}
            - name: ELMA365_TELEMETRIST_METRIC_STORE_DURATION
              value: {{ .Values.appconfig.metricStoreDuration | default "24h" | quote }}
            - name: ELMA365_TELEMETRIST_REPORT_MANUAL_TASK_TIMEOUT
              value: {{ .Values.appconfig.reportManualTaskTimeout | default "5m" | quote }}
            - name: ELMA365_TELEMETRIST_REPORT_MANUAL_TASK_STORE_DURATION
              value: {{ .Values.appconfig.reportManualTaskStoreDuration | default "10m" | quote }}
            - name: ELMA365_TELEMETRIST_TRACE_STORE_DURATION_SAAS
              value: {{ .Values.appconfig.traceStoreDurationSaaS | default "15m" | quote }}
            - name: ELMA365_TELEMETRIST_TRACE_STORE_DURATION_ONPREMISES
              value: {{ .Values.appconfig.traceStoreDurationOnPremises | default "240h" | quote }}
            - name: ELMA365_TELEMETRIST_TRACE_CLEANUP_INTERVAL
              value: {{ .Values.appconfig.traceCleanupInterval | default "15m" | quote }}
            - name: ELMA365_TELEMETRIST_TRACE_METADATA_CACHE_TTL
              value: {{ .Values.appconfig.traceMetadataCacheTtl | default "15m" | quote }}
            {{- if .Values.global.monitoring }}
            {{- if .Values.global.monitoring.lowcode }}
            - name: ELMA365_OTELIER_PROMETHEUS_EXPORTER_ENABLED
              value: {{ .Values.global.monitoring.lowcode.metricExportEnabled | default false | quote }}
            {{- else }}
            - name: ELMA365_OTELIER_PROMETHEUS_EXPORTER_ENABLED
              value: "false"
            {{- end }}
            {{- end }}
          {{- if .Values.global.helmLibrary }}
            {{- include "helm-library.deployment.env" . | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
      {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.deployment.securityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.probes" . | indent 10 }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts" . | indent 10 }}
          {{- include "helm-library.deployment.lifecycle" . | indent 10 }}
        {{- include "helm-library.deployment.volumes" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
