{{- if eq (toString .Values.global.openshift) "true" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "notifier.name" . }}
spec:
  host: {{ .Values.global.host }}
  path: "/ws/"
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: {{ template "notifier.name" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
