{{- $serviceName := include "collector.name" . -}}
{{- if semverCompare ">=1.21-0" (include "kubeVersion" .) -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ $serviceName }}-collections-items-archiving
  labels:
    app: {{ $serviceName }}
    tier: elma365-job
    chart: {{ template "collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  startingDeadlineSeconds: {{ default 300 .Values.global.cronStartingDeadlineSeconds }}
  concurrencyPolicy: Replace
  schedule: {{ .Values.appconfig.archiving.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ default 300 .Values.global.cronTtlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ default 120 .Values.global.cronActiveDeadlineSeconds }}
      template:
        metadata:
          labels:
            job: archiving-collector
            tier: elma365
            sidecar.istio.io/inject: "false"
          annotations:
            linkerd.io/inject: disabled
        spec:
          {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.job.podSecurityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.scheduling" . | indent 10 }}
          {{- end }}
          imagePullSecrets:
          {{- range .Values.global.image.pullSecret }}
            - name: {{ . }}
          {{- end }}
          containers:
            - name: collections-items-archiving
              image: "{{ .Values.global.image.repository }}/docker/toolkit/curl:8.2.1"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              args:
                - /bin/sh
                - -ec
                - 'curl --fail -m {{ default 30 .Values.global.cronActiveDeadlineSeconds }} -X POST http://{{ template "collector.name" . }}:{{ .Values.global.http_port }}/jobs/archiving'
            {{- if .Values.global.helmLibrary }}
              securityContext:
                {{- include "helm-library.job.securityContext" . | nindent 16 }}
              {{- include "helm-library.cronjobs.resources" . | indent 14 }}
            {{- end }}
          restartPolicy: OnFailure
