global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  companies:
    - '*'
  openshift: false
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
images:
  service: ci-8ff20b4e
  setup: ci-5b0a42d9
image:
  repository: {}
  pullSecret: {}
appconfig:
  hydraAdminURL: "http://hydra:4445"
  loginEndpoint: "https://elma365.ru/ext-api/oidc-adaptor/login"
  vahterCookieName: "vtoken"
  corsHosts:
    production:
      - elma365.ru
      - elma365.net
      - elma365.com
    staging:
      - s-elma365.ru
      - s-elma365.net
      - s-elma365.com
    _default:
      - '*'
ingress:
  path: "/ext-api/oidc-adaptor/"
  annotations: {}
  additionalHosts: []
autoscaling: {}
nameOverride: hydra-adaptor
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
rabbitmq: {}
annotations:
  ci.elma365.com/commit: "33f307cf"
  ci.elma365.com/checksum: "5b0a42d9"
  ci.elma365.com/job_id: "3467502"
  ci.elma365.com/timestamp: "2025-07-15T17:51:59+04:00"
  ci.elma365.com/pipeline_id: "606903"
