{{- if eq (toString .Values.global.provisioner) "deckhouse" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: deckhouse-ns-patcher
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-28"
spec:
  template:
    metadata:
      name: deckhouse-ns-patcher
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        linkerd.io/inject: disabled
    spec:
      serviceAccountName: internal-kubectl-secrets
      imagePullSecrets:
      {{- range .Values.global.kubectl.pullSecret }}
        - name: {{ . }}
      {{- end }}
      containers:
      - name: deckhouse-ns-patcher
        image: "{{ .Values.global.kubectl.repository }}/docker/toolkit/kubectl:{{ .Values.global.kubectl.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "if ! (kubectl label namespace {{ .Release.Namespace }} prometheus.deckhouse.io/monitor-watcher-enabled=true && kubectl label namespace {{ .Release.Namespace }} prometheus.deckhouse.io/scrape-configs-watcher-enabled=true && kubectl label namespace {{ .Release.Namespace }} security.deckhouse.io/pod-policy=privileged); then exit 0; fi"]
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp
      volumes:
      - name: secret-volume
        emptyDir: {}
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deckhouse-patcher
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","update","create","patch","label"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deckhouse-patcher
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
subjects:
  - kind: ServiceAccount
    name: internal-kubectl-secrets
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: deckhouse-patcher
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
