{{- if .Values.linkerd.identity.externalCA }}
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-identity-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/tls
data:
  ca.crt: {{ .Files.Get "ssl/linkerd/ca.crt" | b64enc }}
  tls.crt: {{ .Files.Get "ssl/linkerd/issuer.crt" | b64enc }}
  tls.key: {{ .Files.Get "ssl/linkerd/issuer-private.pem" | b64enc }}
{{- end }}