global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels:
    event-producer: "true"
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  managedServices:
    enabled: false
    namespace: elma365-applets
    defaultStorageClass: "longhorn"
    watchableConfigMap:
      enabled: false
      name: 'elma365-babysitter-config'
  lifecycle: {}
images:
  service: ci-2a02ac98
  monitor: ci-b3dc7b12
image:
  repository: {}
  pullSecret: {}
fullnameOverride: babysitter
nameOverride: babysitter
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
resourcesJobs: {}
resources: {}
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
k8s:
  manageableNamespace: "dev-teamx"
  defaultStorageClass: "longhorn"
sidecar:
  port: "3003"
  image: ""
  pullSecret: "yandexsecret"
storage:
  defaultSize: "1Gi"
  usageThreshold: 0.6
  expandMultiplier: 1.5
  expandPeriod: 5
  expandTimeout: 5
  storageExpandConcurrency: 100
annotations:
  ci.elma365.com/commit: "0f5bb984"
  ci.elma365.com/checksum: "2a02ac98"
  ci.elma365.com/job_id: "3512000"
  ci.elma365.com/timestamp: "2025-08-04T11:17:13+04:00"
  ci.elma365.com/pipeline_id: "612161"
