apiVersion: v2
appVersion: 0.1.0
description: Elma365 instagram service
home: https://git.elewise.com/elma365/messenger-instagram
name: messenger-instagram
sources:
- dreg.elewise.com:5005/elma365/messenger-instagram
type: application
version: 0.1.0
