{{- if eq .Values.global.solution "saas" -}}
{{- if pluck .Values.global.env .Values.ingress.enabled | first | default .Values.ingress.enabled._default -}}
apiVersion: v1
kind: Secret
type: Opaque
data:
  auth: {{ (print "apiuser:{PLAIN}" (index .Values.ingress.password)) | b64enc | quote }}
metadata:
  name: ingress-balancer-password
  labels:
    {{- include "balancer.labels" . | nindent 4 }}
{{- end }}
{{- end }}
---
{{- if eq .Values.global.solution "saas" }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-route53
  labels:
    {{- include "balancer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.aws }}
  {{- if .Values.global.aws.route53 }}
  region: {{ default "us-east-1" .Values.global.aws.route53.region | b64enc | quote }}
  access_key_id: {{ default "" .Values.global.aws.route53.accessKeyID | b64enc | quote }}
  secret_access_key: {{ default "" .Values.global.aws.route53.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
