global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe: {}
  nodeSelector: {}
  podSecurityContext: {}
  securityContext: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-f081f80a
image:
  repository: {}
  pullSecret: {}
appconfig:
  tokenTTL: 672h1m
  disableGraphCommonCache: false
secrets:
  vahter:
    create:
      develop: true
      _default: false
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIC4DCCAkmgAwIBAgIJAI5CeUT3SGdCMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJSVTEQMA4GA1UECAwHSXpoZXZzazEQMA4GA1UEBwwHSXpoZXZzazENMAsGA1UECgwERWxtYTEQMA4GA1UECwwHZWxtYTM2NTEUMBIGA1UEAwwLZWxtYTM2NS5jb20xHjAcBgkqhkiG9w0BCQEWD2VsbWEzNjVAbWFpbC5ydTAeFw0xNzExMjgwOTA5MjhaFw0xNzEyMjgwOTA5MjhaMIGIMQswCQYDVQQGEwJSVTEQMA4GA1UECAwHSXpoZXZzazEQMA4GA1UEBwwHSXpoZXZzazENMAsGA1UECgwERWxtYTEQMA4GA1UECwwHZWxtYTM2NTEUMBIGA1UEAwwLZWxtYTM2NS5jb20xHjAcBgkqhkiG9w0BCQEWD2VsbWEzNjVAbWFpbC5ydTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA4jc+MhV2NXC9tfN9+TguqbSlVE6H0u9kg7voy8ZdW0ZhJumL1Wc/BiBop8FzUu9xWZNZLl1wvIPH4jQ/AumeLAlGuERKWlwwUo8hk4nSmXX+TUFyJhcVP6ykU0xC6eziKTikjiMeLRWN4NV/AXXsBsnMrqPCN14q46qzgDkaMekCAwEAAaNQME4wHQYDVR0OBBYEFB+IgCz+TtJZZZiQ8lp+GSVZgpSQMB8GA1UdIwQYMBaAFB+IgCz+TtJZZZiQ8lp+GSVZgpSQMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADgYEAvB6j7uoTqzC3Q26Udif5/sLjomRlHxnH4wQTQOnH2l61T8bUiC0JYi+99SjP2U4G23B+SEeKCXA/Srpj08L1JYXKYFX7kAAULraLStAbgDt5T+rGNuCdiB8CmCI/NoIBaByIREKzbWU5A9HAo18prQZkJAzQRFcp/Up/ATL+f30=
      -----END CERTIFICATE-----
  tls:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIC4DCCAkmgAwIBAgIJAI5CeUT3SGdCMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJSVTEQMA4GA1UECAwHSXpoZXZzazEQMA4GA1UEBwwHSXpoZXZzazENMAsGA1UECgwERWxtYTEQMA4GA1UECwwHZWxtYTM2NTEUMBIGA1UEAwwLZWxtYTM2NS5jb20xHjAcBgkqhkiG9w0BCQEWD2VsbWEzNjVAbWFpbC5ydTAeFw0xNzExMjgwOTA5MjhaFw0xNzEyMjgwOTA5MjhaMIGIMQswCQYDVQQGEwJSVTEQMA4GA1UECAwHSXpoZXZzazEQMA4GA1UEBwwHSXpoZXZzazENMAsGA1UECgwERWxtYTEQMA4GA1UECwwHZWxtYTM2NTEUMBIGA1UEAwwLZWxtYTM2NS5jb20xHjAcBgkqhkiG9w0BCQEWD2VsbWEzNjVAbWFpbC5ydTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA4jc+MhV2NXC9tfN9+TguqbSlVE6H0u9kg7voy8ZdW0ZhJumL1Wc/BiBop8FzUu9xWZNZLl1wvIPH4jQ/AumeLAlGuERKWlwwUo8hk4nSmXX+TUFyJhcVP6ykU0xC6eziKTikjiMeLRWN4NV/AXXsBsnMrqPCN14q46qzgDkaMekCAwEAAaNQME4wHQYDVR0OBBYEFB+IgCz+TtJZZZiQ8lp+GSVZgpSQMB8GA1UdIwQYMBaAFB+IgCz+TtJZZZiQ8lp+GSVZgpSQMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADgYEAvB6j7uoTqzC3Q26Udif5/sLjomRlHxnH4wQTQOnH2l61T8bUiC0JYi+99SjP2U4G23B+SEeKCXA/Srpj08L1JYXKYFX7kAAULraLStAbgDt5T+rGNuCdiB8CmCI/NoIBaByIREKzbWU5A9HAo18prQZkJAzQRFcp/Up/ATL+f30=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXAIBAAKBgQDiNz4yFXY1cL218335OC6ptKVUTofS72SDu+jLxl1bRmEm6YvVZz8GIGinwXNS73FZk1kuXXC8g8fiND8C6Z4sCUa4REpaXDBSjyGTidKZdf5NQXImFxU/rKRTTELp7OIpOKSOIx4tFY3g1X8BdewGycyuo8I3XirjqrOAORox6QIDAQABAoGAIYiU5LG/wy5CQR2mN/J3IFsSAwxdIAyytsB9Qu/V2Pj23+DRBMJ4Wj0lpnCL2uh5whCQsMnTM27Ji6O5D4J4GsGYNvU0hPhoITcuj88T3xCZZ3Zsb/42Rphp/IVm7+ssg7WNhDo3KwixS/pSr2zMmh9oNWOOfHviyFrviQ9xBbECQQD9YW525GcliQH1JR6pB+4C+Y72qQ5E2Nq43SlF75nUm4LnnFypo6PGuvWaAXs0z9R2MWcCu7ub+GICm38FQhGtAkEA5I3rj2G6sUnbmEd6ZRvGPGFrDckbwbusvZXB+w+9jdD+2qhICb1vWxhBzjH7lSSNSj5EIWkj+TzNqQuX7k1ArQJAGRSG0Z/kEdQQ7IoDEeomBgdbvlCXh/sLE1dY2YJQ8Ll/6JsSlPwMnwQsgVT6NA0KU7SqJJwegt7AHM/1b7jNdQJAY+EhcCdlTtTYAlQ6SLU6jGiGQCAC4UcC1lb7zpuyWqdauHOSB6+hWk3fdByjtSmkFS3g2Dj6X5ESzy0h2CIqgQJBANtYPfvXn4TDx3nPoDCeriUE/vzxaRmigFqz5nIyJ6I5CbQI9DQ6mLFx6i0J5h/753UONHu8c6N05A0ARH5S4Us=
      -----END RSA PRIVATE KEY-----
nameOverride: auth
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "384Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "8e137bce"
  ci.elma365.com/checksum: "f081f80a"
  ci.elma365.com/job_id: "3231000"
  ci.elma365.com/timestamp: "2025-05-14T07:42:48+00:00"
  ci.elma365.com/pipeline_id: "577203"
