{{- if or (eq .Values.global.solution "onPremise") ( .Values.global.checkdbs ) }}
{{- if ne (toString .Values.global.checkdbs) "false" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: checkdbs
  labels:
    {{- include "connectionschecker.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: before-hook-creation
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-4"
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        linkerd.io/inject: disabled
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.jobGlobal.podSecurityContext" . | nindent 8 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
      imagePullSecrets:
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
      containers:
        - name: service
          image: "{{ .Values.global.image.repository }}/elma365/connectionschecker/service:{{ .Values.images.service }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "/bin/sh"
            - "-ec"
            - 'sleep 5 && checker check'
          envFrom:
            - secretRef:
                name: elma365-db-connections
                optional: true
        {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.jobGlobal.securityContext" . | nindent 12 }}
          {{- include "helm-library.jobGlobal.resources" . | indent 10 }}
        {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 5
  activeDeadlineSeconds: {{ default 1800 .Values.global.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: 86400
{{- end }}
{{- end }}
