apiVersion: v2
appVersion: 0.1.0
description: Elma365 messengers service
home: https://git.elewise.com/elma365/messengers
name: messengers
sources:
- dreg.elewise.com:5005/elma365/messengers
type: application
version: 0.1.0
