global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  resourcesJobs: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-1d323c2d
image:
  repository: {}
  pullSecret: {}
nameOverride: checkdbs
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resourcesJobs: {}
resources: {}
connectionschecker:
  labels:
    tier: elma365
    action: checkdbs
annotations:
  ci.elma365.com/commit: "9775210d"
  ci.elma365.com/checksum: "1d323c2d"
  ci.elma365.com/job_id: "3548097"
  ci.elma365.com/timestamp: "2025-08-13T10:54:15+04:00"
  ci.elma365.com/pipeline_id: "615427"
