{{- if .Values.global.fulltextsearcher }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fulltextsearcher.name" . }}-secret
  labels:
    {{- include "fulltextsearcher.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  ELMA365_OPENSEARCH_ADDRESSES: {{ .Values.opensearch.addresses | b64enc | quote  }}
  ELMA365_OPENSEARCH_LOGIN: {{ .Values.opensearch.login | b64enc | quote }}
  ELMA365_OPENSEARCH_PASSWORD: {{ .Values.opensearch.password | b64enc | quote }}

{{- end }}
