{
 "title": "ELMA365 top replication",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Namespaces CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (topk by(namespace) (5, namespace:workload_cpu_usage:sum))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top pods by CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (topk(10, rate(container_cpu_usage_seconds_total{namespace=~\"elma365.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (topk by(namespace) (5, namespace:workload_memory_usage:sum))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top pods by Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by(pod) (container_memory_usage_bytes{namespace=~\"elma365.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces Net inbound traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (namespace:workload_net_bytes_received:sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Horizontal Autoscaler Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"elma365.*\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  }
 ]
}