## Настройки linkerd
linkerd:
## DNS-имя домена Kubernetes
  clusterDomain: cluster.local
## добавляет  ресурс PodSecurityPolicy (устарело начиная с версии k8s v1.21)
  enablePSP: false
## отключить heartbeat
  disableHeartBeat: false
## сертификат CA
  identityTrustAnchorsPEM: |  
      -----BEGIN CERTIFICATE-----
      MIIBnjCCAUWgAwIBAgIUZe5uQz19Z8ushw2UgwZZe1HnmeswCgYIKoZIzj0EAwIw
      JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwOTE0
      MTQyNzEzWhcNMzUwOTEyMTQyNzEzWjAlMSMwIQYDVQQDDBpyb290LmxpbmtlcmQu
      Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCGELXmskmS5
      XXhRZUFleZ9MYvoNq3HRFrU68XICjkXasX0HT3G4m1a0htayjv6U+Wjfeb5gt2Ae
      ZNpj/4SfA26jUzBRMB0GA1UdDgQWBBTnPkkBJINO7YxNpILKOTMva6nHfDAfBgNV
      HSMEGDAWgBTnPkkBJINO7YxNpILKOTMva6nHfDAPBgNVHRMBAf8EBTADAQH/MAoG
      CCqGSM49BAMCA0cAMEQCIBw07Ut1Q4PTg7JpKuvTz2UnQA04tnGWqybz4J26CInR
      AiBOuKJWv1ByDhwQaLfNIGC1e9bCgtU3nc7xkmy4SDsgfw==
      -----END CERTIFICATE-----
  identity:
    issuer:
      tls:
## сертификат эмитента
        crtPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBszCCAVmgAwIBAgIUbEZqcXSnBojIEP5rWC9vYJvlVXUwCgYIKoZIzj0EAwIw
          JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwOTE0
          MTQzODU1WhcNMzUwOTEyMTQzODU1WjApMScwJQYDVQQDDB5pZGVudGl0eS5saW5r
          ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQAaSvl
          6NjtzLAXQB16OFFJqWEEHR8aO44oYogM60Cga3Z5ZNrgV5JDDU78ifLe/r+oOiuf
          Yto+UdYTma1hOHs1o2MwYTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
          hjAdBgNVHQ4EFgQUOuQG8QaE1an4Km5YJujl2440OhQwHwYDVR0jBBgwFoAU5z5J
          ASSDTu2MTaSCyjkzL2upx3wwCgYIKoZIzj0EAwIDSAAwRQIgR0sMRgwKErhlUI+p
          uSwNDLx7YYa1GPh5gWJJYoHbc2cCIQC0cUZ7jjtn8w4uOtqFKL12vjdB3JdpANm9
          A+PBnrFpag==
          -----END CERTIFICATE-----
## закрытый ключ эмитента
        keyPEM: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIIGozfHoEDL7ytV45TLtjXSigBeEXMhyJ8ElT/VydbVYoAoGCCqGSM49
          AwEHoUQDQgAEAGkr5ejY7cywF0AdejhRSalhBB0fGjuOKGKIDOtAoGt2eWTa4FeS
          Qw1O/Iny3v6/qDorn2LaPlHWE5mtYTh7NQ==
          -----END EC PRIVATE KEY-----
##
## параметры для обеспечения высокой доступности
  controllerReplicas: 3
  enablePodDisruptionBudget: true
  deploymentStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  enablePodAntiAffinity: true
  proxy:
## параметры подключения к приватному registry
    image:
## адрес и путь для приватного registry
      name: hub.elma365.tech/docker/addons/linkerd/proxy
      version: "stable-2.14.10"  
    resources:
       cpu:
         request: 100m
       memory:
         limit: 250Mi
         request: 20Mi
  controllerResources: &controller_resources
    cpu: &controller_resources_cpu
      limit: ""
      request: 100m
    memory:
      limit: 250Mi
      request: 50Mi
  destinationResources: *controller_resources
  identityResources:
    cpu: *controller_resources_cpu
    memory:
      limit: 250Mi
      request: 10Mi
  heartbeatResources: *controller_resources
  proxyInjectorResources: *controller_resources
  webhookFailurePolicy: Ignore
  spValidatorResources: *controller_resources
##
# Параметр подключения сбора метрик
  podMonitor:
    enabled: true
#
## параметры подключения к приватному registry
## адрес и путь для приватного registry
  controllerImage: hub.elma365.tech/docker/addons/linkerd/controller
  controllerImageVersion: "stable-2.14.10"
  policyController:
    image:
## адрес и путь для приватного registry
      name: hub.elma365.tech/docker/addons/linkerd/policy-controller
      version: "stable-2.14.10"
  proxyInit:
    image:
## адрес и путь для приватного registry
      name: hub.elma365.tech/docker/addons/linkerd/proxy-init
      version: "v2.2.3"
## секрет с правами доступа к приватному registry должен быть создан вручную, зашифрованный в Base64
#  imagePullSecrets:
#    - name: myRegistryKeySecretName