{{- if .Values.global.hubEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkhub.name" . }}-connections
  labels:
    {{- include "linkhub.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  password: 'CHANGEME'
{{- end }}
