{{- if eq .Values.global.solution "onPremise" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
{{- if not .Values.global.chart }}
  namespace: elma365-system
{{- end }}
  labels:
    tier: elma365
    action: bootstrap
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        linkerd.io/inject: disabled
    spec:
      imagePullSecrets:
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.jobGlobal.podSecurityContext" . | nindent 8 }}
      {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
      containers:
        - name: bootstrap
          image: "{{ .Values.global.image.repository }}/docker/toolkit/curl:8.2.1"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "/bin/sh"
            - "-ec"
            - 'sleep 15 && curl --fail -m {{ default 3000 .Values.global.activeDeadlineSeconds }} -X PUT -H "Content-Type: application/json" http://deploy.{{ default "default" .Release.Namespace }}.svc:3000/migration/init'
        {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.jobGlobal.securityContext" . | nindent 12 }}
          {{- include "helm-library.jobGlobal.resources" . | indent 10 }}
        {{- end }}
      restartPolicy: OnFailure
  backoffLimit: {{ default 5 .Values.global.backoffLimit }}
  activeDeadlineSeconds: {{ default 3000 .Values.global.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: 120
{{- end }}
