{
 "title": "event-bus",
 "description": "Process status published by Go prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, region)" } },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(up{job=~\"main\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(up{cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(up{container=\"$service\",cluster=\"$cluster\",namespace=\"$namespace\"})"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Successful Passes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(elma365_eventbus_trace_rules_success_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$__rate_interval])",
     "legendFormat": "{{company}} {{rule}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Passes Of Any Of The Rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(elma365_eventbus_trace_rules_fail_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$__rate_interval])",
     "legendFormat": "{{company}} {{rule}}"
    }
   ]
  },
  {
   "title": "Trace Events Stack Size Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(elma365_eventbus_trace_events_stack_size_count{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$__rate_interval])",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Trace Rules Condition Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(elma365_eventbus_trace_rules_condition_size_count{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$__rate_interval])",
     "legendFormat": "{{company}} {{rule}}"
    }
   ]
  },
  {
   "title": "Trace Handle System Subscriptions Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(elma365_eventbus_trace_handle_system_subscriptions_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$__rate_interval])",
     "legendFormat": "{{company}} expired={{expired}}/{{handlerType}}/{{eventType}}"
    }
   ]
  },
  {
   "title": "Trace Handle Module Subscriptions Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(elma365_eventbus_trace_handle_module_subscriptions_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$__rate_interval])",
     "legendFormat": "{{company}} {{enabledModule}}/{{handlerType}}/{{eventType}}"
    }
   ]
  }
 ]
}