apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-bus-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
subjects:
  - kind: ServiceAccount
    name: event-bus-sa
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
