apiVersion: v2
appVersion: 0.1.0
description: Elma365 vkontakte service
home: https://git.elewise.com/elma365/messenger-vkontakte
name: messenger-vkontakte
sources:
- dreg.elewise.com:5005/elma365/messenger-vkontakte
type: application
version: 0.1.0
