- alert: billing down
  annotations:
    title: "Instance  down"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Instance of billing has been down for more than 3 minute.
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    up {app='billing'} == 0
  for: 3m
  labels:
    severity: critical
- alert: Low response
  annotations:
    title: "Low response rate"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Response rate of billing less than 95% for more than 5 minute.
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    sum(irate(response_total{app='billing', classification='success', direction='inbound'}[1m])) 
    / sum(irate(response_total{app='billing', direction='inbound'}[1m])) < 0.95
  for: 5m
  labels:
    severity: critical
- alert: Long latencies for event delivery
  annotations:
    title: "Long latencies for event delivery"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Long latencies for event delivery for billing
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    histogram_quantile(0.99, sum(irate(eventbus_delivery_duration_bucket{pod=~"billing.*"}[1m]))
    by (le, namespace, pod)) > 500
  for: 5m
  labels:
    severity: critical
- alert: billing http request duration too high 
  annotations:
    title: "billing http request duration too high for 5 min"
    timestamp: > 
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      billing http request duration too high for 5 min
      VALUE = {{ $value }}
      LABELS = {{ $labels }}      
  expr: |-
    histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job="billing"}[5m])) by (le,namespace)) > 3
  for: 5m
  labels:
    severity: critical 
       