{{- if semverCompare ">=1.21-0" (include "kubeVersion" .) -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: clean-sessions-tables
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  startingDeadlineSeconds: {{ default 300 .Values.global.cronStartingDeadlineSeconds }}
  concurrencyPolicy: Replace
  schedule: "0 4 * * 1"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ default 300 .Values.global.cronTtlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ default 120 .Values.global.cronActiveDeadlineSeconds }}
      template:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
          annotations:
            linkerd.io/inject: disabled
        spec:
          {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.job.podSecurityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.scheduling" . | indent 10 }}
          {{- end }}
          imagePullSecrets:
          {{- range .Values.global.image.pullSecret }}
            - name: {{ . }}
          {{- end }}
          containers:
            - name: clean-sessions-tables-curl
              image: "{{ .Values.global.image.repository }}/docker/toolkit/curl:8.2.1"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              args:
                - /bin/sh
                - -ec
                - 'curl --fail -m {{ default 300 .Values.global.cronActiveDeadlineSeconds }} -X GET http://{{ include "main.name" . }}:{{ .Values.global.http_port }}/system/sessions/clean-tables'
            {{- if .Values.global.helmLibrary }}
              securityContext:
                {{- include "helm-library.job.securityContext" . | nindent 16 }}
              {{- include "helm-library.cronjobs.resources" . | indent 14 }}
            {{- end }}
          restartPolicy: OnFailure
