global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  resourcesJobs: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-44f43632
image:
  repository: {}
  pullSecret: {}
nameOverride: checkdbs
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resourcesJobs: {}
resources: {}
connectionschecker:
  labels:
    tier: elma365
    action: checkdbs
annotations:
  ci.elma365.com/commit: "1cbd4960"
  ci.elma365.com/checksum: "44f43632"
  ci.elma365.com/job_id: "3470268"
  ci.elma365.com/timestamp: "2025-07-24T10:03:10+00:00"
  ci.elma365.com/pipeline_id: "607262"
