- alert: deploy down
  annotations:
    title: "Instance  down"
    timestamp: >
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Instance of deploy has been down for more than 3 minute.
      VALUE = {{ $value }}
      LABELS = {{ $labels }}
  expr: |-
    up {app='deploy'} == 0
  for: 3m
  labels:
    severity: critical
- alert: Low response
  annotations:
    title: "Low response rate"
    timestamp: >
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Response rate of deploy less than 95% for more than 5 minute.
      VALUE = {{ $value }}
      LABELS = {{ $labels }}
  expr: |-
    sum(irate(response_total{app='deploy', classification='success', direction='inbound'}[1m]))
    / sum(irate(response_total{app='deploy', direction='inbound'}[1m])) < 0.95
  for: 5m
  labels:
    severity: critical
- alert: Long latencies for event delivery
  annotations:
    title: "Long latencies for event delivery"
    timestamp: >
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Long latencies for event delivery for deploy
      VALUE = {{ $value }}
      LABELS = {{ $labels }}
  expr: |-
    histogram_quantile(0.99, sum(irate(eventbus_delivery_duration_bucket{pod=~"deploy.*"}[1m]))
    by (le, namespace, pod)) > 500
  for: 5m
  labels:
    severity: critical
- alert: Latency long
  annotations:
    title: "Too long latency"
    timestamp: >
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Latency of service deploy is too long for 5m
      VALUE = {{ $value }}
      LABELS = {{ $labels }}
  expr: |-
    histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{pod=~'deploy.*',
    direction='inbound'}[1m])) by (le, pod)) > 500
  for: 5m
  labels:
    severity: critical
- alert: Create company failed
  annotations:
    title: "Create company failed"
    timestamp: >
      time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
    description: |-
      Create company failed
      VALUE = {{ $value }}
      LABELS = {{ $labels }}
  expr: |-
    increase(elma365_deploy_create_company_total{code!="201"}[1m])!=0
  for: 0m
  labels:
    severity: critical
