apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elma365-dbs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/lovemetrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 2025.7.8/elma365-dbs
    helm:
      valueFiles:
        - values-elma365-dbs.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elma365-dbs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
