apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elma365-dbs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/LovemeTrue/ArgoCI-CD.git
    targetRevision: main
    path: 2025.8.7/elma365-dbs
    helm:
      valueFiles:
        - values-elma365-dbs.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elma365-dbs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  ignoreDifferences:
    - group: batch
      kind: Job
      name: checkdbs
      namespace: elma365
      jsonPointers:
        - /metadata/finalizers
    
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Важно для секретов!
      