apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    # Принудительное обновление секретов
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: default
  source:
    repoURL: https://github.com/LovemeTrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 0/monitoring
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - Replace=true
        