apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/lovemetrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 0/linkerd
    helm:
      valueFiles:
        - values-linkerd.yaml
      parameters:
        - name: linkerd.identityTrustAnchorsPEM
          value: |
            -----BEGIN CERTIFICATE-----
            MIIBnjCCAUWgAwIBAgIUZe5uQz19Z8ushw2UgwZZe1HnmeswCgYIKoZIzj0EAwIw
            JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwOTE0
            MTQyNzEzWhcNMzUwOTEyMTQyNzEzWjAlMSMwIQYDVQQDDBpyb290LmxpbmtlcmQu
            Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCGELXmskmS5
            XXhRZUFleZ9MYvoNq3HRFrU68XICjkXasX0HT3G4m1a0htayjv6U+Wjfeb5gt2Ae
            ZNpj/4SfA26jUzBRMB0GA1UdDgQWBBTnPkkBJINO7YxNpILKOTMva6nHfDAfBgNV
            HSMEGDAWgBTnPkkBJINO7YxNpILKOTMva6nHfDAPBgNVHRMBAf8EBTADAQH/MAoG
            CCqGSM49BAMCA0cAMEQCIBw07Ut1Q4PTg7JpKuvTz2UnQA04tnGWqybz4J26CInR
            AiBOuKJWv1ByDhwQaLfNIGC1e9bCgtU3nc7xkmy4SDsgfw==
            -----END CERTIFICATE-----
        - name: linkerd.identity.issuer.tls.crtPEM
          values: |
            -----BEGIN CERTIFICATE-----
            MIIBszCCAVmgAwIBAgIUbEZqcXSnBojIEP5rWC9vYJvlVXUwCgYIKoZIzj0EAwIw
            JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwOTE0
            MTQzODU1WhcNMzUwOTEyMTQzODU1WjApMScwJQYDVQQDDB5pZGVudGl0eS5saW5r
            ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQAaSvl
            6NjtzLAXQB16OFFJqWEEHR8aO44oYogM60Cga3Z5ZNrgV5JDDU78ifLe/r+oOiuf
            Yto+UdYTma1hOHs1o2MwYTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
            hjAdBgNVHQ4EFgQUOuQG8QaE1an4Km5YJujl2440OhQwHwYDVR0jBBgwFoAU5z5J
            ASSDTu2MTaSCyjkzL2upx3wwCgYIKoZIzj0EAwIDSAAwRQIgR0sMRgwKErhlUI+p
            uSwNDLx7YYa1GPh5gWJJYoHbc2cCIQC0cUZ7jjtn8w4uOtqFKL12vjdB3JdpANm9
            A+PBnrFpag==
            -----END CERTIFICATE-----
        - name: linkerd.identity.issuer.tls.keyPEM
          values: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIIGozfHoEDL7ytV45TLtjXSigBeEXMhyJ8ElT/VydbVYoAoGCCqGSM49
            AwEHoUQDQgAEAGkr5ejY7cywF0AdejhRSalhBB0fGjuOKGKIDOtAoGt2eWTa4FeS
            Qw1O/Iny3v6/qDorn2LaPlHWE5mtYTh7NQ==
            -----END EC PRIVATE KEY-----
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      