apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lovemetrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 0/linkerd
    helm:
      valueFiles:
        - values-linkerd.yaml
      parameters:
        - name: linkerd.identity.externalCA
          value: "true"
        - name: linkerd.identity.issuer.scheme
          value: "kubernetes.io/tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true