{{- if eq (toString .Values.global.openshift) "true" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/rewrite-target: /public
  name: {{ template "web-forms.name" . }}
spec:
  host: {{ .Values.global.host }}
  path: "/web-forms"
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: {{ template "web-forms.name" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
