apiVersion: v2
appVersion: 1.16.0
description: Сервис документооборота
home: https://git.elewise.com/elma365/docflow
name: docflow
sources:
- dreg.elewise.com:5005/elma365/docflow
type: application
version: 0.1.0
