{{/*
Prometheus Exporter ServiceMonitor for Otelier.
*/}}
{{- if eq (toString .Values.global.monitoring.enabled) "true" }}
{{- if ($.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- if eq (toString .Values.global.monitoring.lowcode.metricExportEnabled) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: {{ template "otelier.name" . }}
    {{- if eq (toString .Values.global.monitoring.provisioner) "deckhouse" }}
    prometheus: main
    {{- end }}
  name: {{ template "otelier.name" . }}-pe-servicemonitor
spec:
  endpoints:
    - port: otlp-prom
    {{- if ne (toString .Values.global.monitoring.provisioner) "deckhouse" }}
      path: /metrics
      interval: {{ default "30s" .Values.global.monitoring.metrics.interval }}
      honorLabels: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "otelier.name" . }}
{{- end }}
{{- end }}
{{- end }}
