global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
images:
  service: ci-92a4972b
  setup: ci-c535a0c1
image:
  repository: {}
  pullSecret: {}
fullnameOverride: integrations
nameOverride: integrations
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "500m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
appconfig:
  availableIntegrations:
    - all
  SamlInsecureFetchMetadata: false
  ldapTimeout: '55s'
  ldapJobTTL: '2m'
  ldapJobDelayBetweenAttempts: '10s'
  aesCryptKey: 'NOPERsiCEdiaNOBatEaRnmeaTIoNcOnc'
rabbitmq:
  vhName: {}
annotations:
  ci.elma365.com/commit: "740a03b5"
  ci.elma365.com/checksum: "c535a0c1"
  ci.elma365.com/job_id: "3554739"
  ci.elma365.com/timestamp: "2025-08-18T16:03:16+04:00"
  ci.elma365.com/pipeline_id: "616027"
