{{- if eq .Values.global.solution "onPremise" }}
{{- if semverCompare ">=1.21-0" (include "kubeVersion" .) -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: bill-keychecker
spec:
  schedule: "0 */3 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  startingDeadlineSeconds: {{ default 300 .Values.global.cronStartingDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ default 300 .Values.global.cronTtlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ default 120 .Values.global.cronActiveDeadlineSeconds }}
      template:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
          annotations:
            linkerd.io/inject: disabled
        spec:
          {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.job.podSecurityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.scheduling" . | indent 10 }}
          {{- end }}
          imagePullSecrets:
          {{- range .Values.global.image.pullSecret }}
            - name: {{ . }}
          {{- end }}
          containers:
            - name: keychecker
              image: "{{ .Values.global.image.repository }}/docker/toolkit/curl:8.2.1"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - curl --fail -m {{ default 30 .Values.global.cronActiveDeadlineSeconds }} http://billing:3000/external/license/checkkey
            {{- if .Values.global.helmLibrary }}
              securityContext:
                {{- include "helm-library.job.securityContext" . | nindent 16 }}
              {{- include "helm-library.cronjobs.resources" . | indent 14 }}
            {{- end }}
          restartPolicy: OnFailure

{{- end }}
