global:
  hubEnabled: false
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: Always
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  cronStartingDeadlineSeconds: ""
  cronTtlSecondsAfterFinished: ""
  cronActiveDeadlineSeconds: ""
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  setup: ci-c0e43ef5
  service: ci-c8a8fb30
image:
  repository: {}
  pullSecret: {}
nameOverride: linkhub
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
autoscaling: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
linkhub:
  labels:
    app: linkhub
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
annotations:
  ci.elma365.com/commit: "7acff5d9"
  ci.elma365.com/checksum: "c0e43ef5"
  ci.elma365.com/job_id: "3467155"
  ci.elma365.com/timestamp: "2025-07-15T17:59:13+04:00"
  ci.elma365.com/pipeline_id: "606869"
