global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  lifecycle: {}
images:
  service: ci-570a886d
image:
  repository: {}
  pullSecret: {}
nameOverride: registrator
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources: {}
nodeSelector: {}
tolerations: []
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
registrator:
  labels:
    app: registrator
annotations:
  ci.elma365.com/commit: "2e7506bd"
  ci.elma365.com/checksum: "570a886d"
  ci.elma365.com/job_id: "3511047"
  ci.elma365.com/timestamp: "2025-08-04T11:13:07+04:00"
  ci.elma365.com/pipeline_id: "612124"
